<?php if (!empty($catalogo)) { ?>
    <?php $cuenta = 0; ?>
    <?php foreach ($catalogo as $key => $articulo) { ?>
        <?php
        if ($cuenta == $pag) {
            break;
        }
        $foto_web = empty($articulo->imagen) ? 'default.jpg' : $articulo->imagen;
        $titulo = strtolower($articulo->descripcion);

        if (!empty(Session::get('login')) && Session::get('perfil_id') == Perfil::DISTRIBUIDOR) {
            $precio_vent = DwOnline::setPrecios($articulo->precio_distribuidor, $articulo->valor);
        } else {
            $precio_vent = DwOnline::setPrecios($articulo->precio_venta, $articulo->valor);
        }
        ?>
        <div class="product product-single" itemtype="http://schema.org/Product" itemscope>
            <meta itemprop="sku" content="<?= $articulo->mpn; ?>" />
            <meta itemprop="productID" content="<?= $articulo->id; ?>" />
            <meta itemprop="inventory" content="<?= $articulo->instock; ?>" />
            <meta itemprop="condition" content="new" />
            <meta itemprop="name" content="<?= substr($titulo, 0, 140); ?>" />
            <meta itemprop="description" content="<?= $titulo; ?>" />
            <div style="display: none;" itemprop="review" itemscope itemtype="http://schema.org/Review"> 
                <span itemprop="name">Calificacion</span>
                <span itemprop="author">Asdinec</span>
                <span itemprop="reviewBody">Excelente producto</span>
                <span itemprop="datePublished"><?= date("Y-m-d") ?></span>
            </div>
            <div style="display: none;" itemprop="offers" itemtype="http://schema.org/Offer" itemscope>
                <link itemprop="url" href="http://asdinec.com/index/producto/sales/" />
                <meta itemprop="availability" content="https://schema.org/InStock" />
                <meta itemprop="priceCurrency" content="USD" />
                <meta itemprop="itemCondition" content="https://schema.org/UsedCondition" />
                <meta itemprop="price" content="<?= $precio_vent ?>" />
                <meta itemprop="priceValidUntil" content="<?= date("Y-m-d") ?>" />
            </div>
            <div class="product-thumb">
                <div class="product-label">
                    <?php if (!empty($articulo->nuevo)) { ?>
                        <span><?= !empty($articulo->nuevo) ? 'Nuevo' : ''; ?></span>
                    <?php } else if (!empty($articulo->onsales)) { ?>
                        <span class="sale"><?= !empty($articulo->onsales) ? 'Oferta' : ''; ?></span>
                    <?php } ?>
                </div>
                <a href="http://asdinec.com/index/detalle/<?= $articulo->id ?>/<?= $articulo->brand ?>/" class="no-load btn main-btn quick-view" itemprop="url" tabindex="-1"><i class="fa fa-pd-expand fa-search-plus"></i> Ver más...</a>
                <img src="http://asdinec.com/img/upload/productos/<?= $foto_web ?>" alt="" id="img-productos" class="imgen-store" itemprop="image">
            </div>
            <div class="product-body">
                <h3 class="product-price">$ <?= $precio_vent ?></h3>
                <div class="product-rating" itemprop="aggregateRating" itemtype="http://schema.org/AggregateRating" itemscope>
                    Stock: <?= $articulo->instock ?>
                    <meta itemprop="reviewCount" content="89" />
                    <meta itemprop="ratingValue" content="4.4" />
                </div>
                <?php if (!empty(Session::get('login')) && Session::get('perfil_id') <= Perfil::SUPERVISOR) { ?>
                    <h5 class="product-single text-danger">SKU: <?= $articulo->sku; ?></h5>
                <?php } ?>
                <h6 class="text-success"><span itemprop="brand"><?= $articulo->marca; ?></span></h6>
                <h6 class="text-success">MODELO: <span itemprop="mpn"><?= $articulo->mpn; ?></span></h6>
                <h2 class="product-name"><?php echo DwHtml::link("index/detalle/$articulo->id/$articulo->brand", substr($articulo->descripcion, 0, 58), array('title' => 'Click para Ver Producto'), NULL, FALSE); ?></h2>

                <div class="product-btns">
                    <?php echo DwForm::open('#', '', array('class' => 'no-ajax form-validate formulario', 'id' => 'formulario')); ?>
                    <fieldset>
                        <input type="hidden" name="href" value="<?= $articulo->id . '/' . $articulo->brand; ?>" />
                        <input type="hidden" name="imagen" value="<?= $foto_web; ?>" />
                        <input type="hidden" name="instock" value="<?= $articulo->instock ?>" />
                        <input type="hidden" name="codigo" value="<?= $articulo->id ?>" />
                        <input type="hidden" name="mpn" value="<?= $articulo->mpn ?>" />
                        <input type="hidden" name="cmd" value="_cart" />
                        <input type="hidden" name="articulo" value="<?= $articulo->descripcion ?>" />
                        <input type="hidden" name="amount" value="<?= $precio_vent ?>" />
                        <input type="hidden" name="discount_amount" value="0" />
                        <div class="item-add-qty">
                            <input id="<?= $articulo->instock ?>" maxlength="3" class="addToCartQuantityBox mask-num" type="text" name="quantity" value="1" autocomplete="off" />
                            <button type="submit" name="submit" class="primary-btn add-to-cart btn-add-item"><i class="fa fa-shopping-cart"></i> COMPRAR</button><br>
                            <?= DwHtml::outLink("https://wa.me/593999301365?text=Me%20gustaría%20comprar%20el%20siguiente%20producto%20codigo:%20$articulo->mpn%20$articulo->descripcion", '<i class="fa fa-pd-expand fa-whatsapp"></i> Pedir x WatsApp', array('class' => 'btn btn-success', 'target' => '_blank')); ?>
                        </div>
                    </fieldset>
                    <?php echo DwForm::close(); ?>
                </div>
            </div>
        </div>
        <?php $cuenta++; ?>
    <?php } ?>
<?php } else { ?>
    <h2 class="text-center">Producto no disponible!</h2>
<?php } ?>