<?php if (!empty($catalogo)) { ?>
    <?php $cuenta = 0; ?>
    <?php foreach ($catalogo as $key => $articulo) { ?>
        <?php
        if ($cuenta == $pag) {
            break;
        }
        $foto_web = empty($articulo->imagen) ? 'default.jpg' : $articulo->imagen;
        if (!empty(Session::get('login')) && Session::get('perfil_id') == Perfil::DISTRIBUIDOR) {
            $precio_vent = DwOnline::setPrecios($articulo->precio_distribuidor, $articulo->valor);
        } else {
            $precio_vent = DwOnline::setPrecios($articulo->precio_venta, $articulo->valor);
        }
        ?>
        <div class="col-md-3 col-sm-6 col-xs-6">
            <div class="product product-single">
                <div class="product-thumb">
                    <div class="product-label">
                        <?php if (!empty($articulo->nuevo)) { ?>
                            <span><?= !empty($articulo->nuevo) ? 'Nuevo' : ''; ?></span>
                        <?php } else if (!empty($articulo->onsales)) { ?>
                            <span class="sale"><?= !empty($articulo->onsales) ? 'Oferta' : ''; ?></span>
                        <?php } ?>
                    </div>
                    <?php echo DwHtml::link("index/detalle/$articulo->id/$articulo->brand", 'Ver m&aacute;s...', array('class' => 'no-load btn main-btn quick-view'), 'fa-search-plus', FALSE); ?>
                    <?= DwHtml::img("upload/productos/$foto_web", "", array('id' => 'img-productos', 'class' => 'imgen-store')) ?>
                </div>
                <div class="product-body">
                    <h3 class="product-price"><?= $precio_vent ?></h3>
                    <div class="product-rating" itemprop="aggregateRating" itemtype="http://schema.org/AggregateRating" itemscope>
                        Stock: <?= $articulo->instock ?>
                        <meta itemprop="reviewCount" content="89" />
                        <meta itemprop="ratingValue" content="4.4" />
                    </div>
                    <?php if (!empty(Session::get('login')) && Session::get('perfil_id') <= Perfil::SUPERVISOR) { ?>
                        <h5 class="product-single text-danger">SKU: <?= $articulo->sku; ?></h5>
                    <?php } ?>
                    <h6 class="text-success"><span itemprop="brand"><?= $articulo->marca; ?></span></h6>
                    <h6 class="text-success">MODELO: <?= $articulo->mpn; ?></h6>
                    <h2 class="product-name"><?php echo DwHtml::link("index/detalle/$articulo->id/$articulo->brand", substr($articulo->descripcion, 0, 58), array('title' => 'Click para Ver Producto', ''), NULL, FALSE); ?></h2>
            <!--<h2 class="product-name"><a href="#"><?= substr($articulo->descripcion, 0, 60) ?></a></h2>-->
                    <div class="product-btns">
                        <?php echo DwForm::open('#', '', array('class' => 'no-ajax form-validate formulario', 'id' => 'formulario')); ?>
                        <fieldset>
                            <input type="hidden" name="href" value="<?= $articulo->id . '/' . $articulo->brand; ?>" />
                            <input type="hidden" name="imagen" value="<?= $foto_web; ?>" />
                            <input type="hidden" name="instock" value="<?= $articulo->instock ?>" />
                            <input type="hidden" name="codigo" value="<?= $articulo->id ?>" />
                            <input type="hidden" name="mpn" value="<?= $articulo->mpn ?>" />
                            <input type="hidden" name="cmd" value="_cart" />
                            <input type="hidden" name="articulo" value="<?= $articulo->descripcion ?>" />
                            <input type="hidden" name="amount" value="<?= $precio_vent ?>" />
                            <input type="hidden" name="discount_amount" value="0" />
                            <div class="item-add-qty">
                                <input id="<?= $articulo->instock ?>" maxlength="3" class="addToCartQuantityBox mask-num" type="text" name="quantity" value="1" autocomplete="off" />
                                <button type="submit" name="submit" class="primary-btn add-to-cart btn-add-item"><i class="fa fa-shopping-cart"></i> COMPRAR</button>
                                <?= DwHtml::outLink("https://wa.me/593999301365?text=Me%20gustaría%20comprar%20el%20siguiente%20producto%20codigo:%20$articulo->mpn%20$articulo->descripcion", '<i class="fa fa-pd-expand fa-whatsapp"></i> Pedir x WatsApp', array('class' => 'primary-btn btn-success', 'target' => '_blank')); ?>
                            </div>
                        </fieldset>
                        <?php echo DwForm::close(); ?>
                    </div>
                </div>
            </div>
        </div>
        <?php $cuenta++; ?>
    <?php } ?>
<?php } else { ?>
    <h2 class="text-center">Producto no disponible!</h2>
<?php } ?>