<table width="640" cellspacing="0" cellpadding="0" border="0" align="center" style="max-width:640px; width:100%;" bgcolor="#FFFFFF">
    <tr>
        <td align="center" valign="top" style="padding:10px;">
            <table width="600" cellspacing="0" cellpadding="0" border="0" align="center" style="max-width:600px; width:100%;">
                <tr>
                    <td align="left" style="padding:10px;"></td>
                </tr>
                <tr>
                    <td align="left" style="padding:10px;">
                        <b>Saludos,</b><br>
                        Eduardo Y&aacute;nez
                    </td>
                </tr>
                <tr>
                    <td align="left" style="padding:10px; font-size: small;">
                        Wsp: +593984022304 | Equipos de Computo, Celulares, servicio t&eacute;cnico y m&aacute;s…<br>Email: soporte@asdinec.com | Skype: asdinec | Web Store: www.asdinec.com
                    </td>
                </tr>
                <tr>
                    <td align="left" style="padding:10px;">
                    </td>
                </tr>
                <tr>
                    <td align="left" style="padding:10px;font-size: small;">
                        Este mensaje ha sido generado de forma autom&aacute;tica.<br>
                        <p>&copy; Copyright <?= APP_NOMBRE ?> | Sistema v<?= APP_VERSION; ?></p>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>