<?php View::flash(); ?>

<?php View::process($page_module, $page_title, $set_title); ?>

<section class="content">

    <?= DwForm::open('', 'post', array('id' => 'form', 'class' => 'dw-validate  no-ajax')); ?>

    <div class="box box-danger">

        <div class="box-body">

            <div class="row">
                <div class="col-md-3">
                    <?= DwForm::text('nombre', array('class' => 'input-medium input-required input-readonly mask-text show-error', 'maxlength' => '60'), $tabla->titulo, 'Nombre Tabla'); ?>
                </div>
                <div class="col-md-3">
                    <?= DwForm::text('impuesto.codigo_impuesto', array('class' => 'input-medium input-required mask-text show-error', 'maxlength' => '4'), NULL, 'Código Impuesto SRI'); ?>
                </div>
                <div class="col-md-3">
                    <?= DwForm::text('impuesto.valor', array('class' => 'input-required mask-num show-error', 'maxlength' => '5'), NULL, 'Valor'); ?>
                </div>
                <div class="col-md-3">
                    <?= DwForm::text('impuesto.valor_retencion', array('class' => 'input-required mask-num show-error', 'maxlength' => '6'), NULL, 'Valor Retencion'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <?= DwForm::textarea('impuesto.impuesto', array('class' => 'input-required mask-text show-error', 'maxlength' => '500'), NULL, 'Nombre Impuesto'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-md-3">
                    <?= DwForm::select('impuesto.tipo_impuesto', array('' => 'Seleccione', 'I' => 'IVA', 'R' => 'RENTA'), array('class' => 'input-required show-errors'), NULL, 'Tipo Impuesto Sri'); ?>
                </div>
                <div class="col-md-3">
                    <?= DwForm::date('impuesto.fecha_inicio', array('class' => 'input-required mask-num show-error', 'maxlength' => '10'), NULL, 'Fecha Inicio'); ?>
                </div>
                <div class="col-md-3">
                    <?= DwForm::date('impuesto.fecha_fin', array('class' => 'mask-num show-error', 'maxlength' => '10'), NULL, 'Fecha Fin'); ?>
                </div>
                <div class="col-md-3">
                    <?= DwForm::select('impuesto.estado', array('' => 'Seleccione', '1' => 'ACTIVO', '0' => 'BLOQUEADO'), array('class' => 'input-break input-required show-errors'), NULL, 'Estado Tabla'); ?>
                </div>
            </div>

            <?php echo DwForm::hidden('impuesto.impuesto_id', NULL, $tabla->id); ?>

            <div class="box box-info">
                <div class="box-footer">
                    <?= DwButton::save('Guardar impuesto'); ?>
                    <?php echo DwForm::cancel(); ?>
                </div>
            </div>

        </div>

    </div>

    <?php echo DwForm::close(); ?>

</section>