<?php View::flash(); ?>

<?php View::process($page_module, $page_title, $set_title); ?>

<section class="content">

    <?= DwForm::open('', 'post', array('id' => 'form', 'class' => 'dw-validate  no-ajax')); ?>

    <div class="box box-danger">

        <div class="box-body">

            <div class="row">
                <div class="col-md-6">
                    <?= DwForm::text('tablas.nombre', array('class' => 'input-medium input-required mask-text show-error', 'maxlength' => '60'), NULL, 'Nombre Tabla'); ?>
                </div>
                <div class="col-md-6">
                    <?= DwForm::text('tablas.abreviatura', array('class' => 'input-medium input-required mask-alpha show-error', 'maxlength' => '3'), NULL, 'Nombre Corto'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <?= DwForm::text('tablas.detalle', array('class' => 'input-medium input-required mask-text show-error', 'maxlength' => '60'), NULL, 'Detalle'); ?>
                </div>
                <div class="col-md-6">
                    <?= DwForm::text('tablas.codigo', array('class' => 'input-medium input-required mask-text show-error', 'maxlength' => '60'), NULL, 'Codigo'); ?>
                </div>
                <div class="col-md-6">
                    <?= DwForm::select('tablas.activo', array('' => 'Seleccione', '1' => 'ACTIVO', '0' => 'BLOQUEADO'), array('class' => 'input-break input-medium input-required mask-pint show-errors'), NULL, 'Estado Tabla'); ?>
                </div>
            </div>

            <div class="box box-info">
                <div class="box-footer">
                    <?= DwButton::save('Guardar tabla'); ?>
                    <?php echo DwForm::cancel(); ?>
                    <?php echo DwForm::focus('tablas.nombre'); ?>
                </div>
            </div>

        </div>

    </div>

    <?php echo DwForm::close(); ?>

</section>