<?php View::flash(); ?>

<?php View::process($page_module, $page_title, $set_title); ?>

<section class="invoice">

    <div class="row">
        <div class="col-xs-12">
            <h2 class="page-header">
                <i class="fa fa-cogs"></i>TABLA IMPUESTO: <?= $tablas->titulo; ?>
                <small class="pull-right">Fecha: <?= date('Y-m-d'); ?></small>
            </h2>
        </div>
    </div>

    <div class="row no-print">
        <div class="col-xs-12">
            <?php echo DwForm::open(); ?>

            <div class="row">
                <div class="col-md-2">
                    <?php echo DwForm::text('tablas.codigo', array('class' => 'input-readonly'), $tablas->detalle, 'Codigo'); ?>
                </div>
                <div class="col-md-5">
                    <?php echo DwForm::text('tablas.titulo', array('class' => 'input-readonly'), $tablas->titulo, 'Nombre Tabla'); ?>
                </div>
            </div>

            <div class="row no-print">
                <div class="col-xs-12">
                    <?php if (Session::get('perfil_id') <= Perfil::ADMIN) { ?>
                        <?php $key_add = Security::setKey($tablas->id, 'add_item'); ?>
                        <?php echo DwButton::back("$modulo/listar"); ?>
                        <?php echo DwHtml::button("$modulo/crear/$key_add/", 'item', array('class' => 'btn-success btn-agrega-articulod'), 'fa-plus', APP_AJAX); ?>
                    <?php } ?>
                </div>
            </div>


            <?php echo DwForm::close(); ?>


            <div class="btn-toolbar btn-toolbar-top">
                <div class="btn-actions">



                </div>
            </div>

            <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
                <thead>
                    <tr>
                        <th>NUM</th>
                        <th>TIPO</th>
                        <th>CODIGO IMPUESTO</th>
                        <th>VALOR</th>
                        <th>VALOR RETENCION</th>
                        <th>NOMBRE IMPUESTO</th>
                        <th>FECHA INICIO</th>
                        <th>FECHA FIN</th>
                        <th>ESTADO</th>
                        <?php if (Session::get('perfil_id') <= Perfil::ADMIN) { ?>
                            <th class="btn-actions col-blocked text-center  ">ACCIONES</th>
                        <?php } ?>
                    </tr>
                </thead>
                <tbody>
                    <?php $counter = 1; ?>
                    <?php foreach ($impuestos->items as $row): ?>
                        <?php $key_mod = Security::setKey($row->id, 'mod_item'); ?>
                        <?php $key_ina = Security::setKey($row->id, 'inactivar_item'); ?>
                        <?php $key_rea = Security::setKey($row->id, 'reactivar_item'); ?>
                        <?php $key_del = Security::setKey($row->id, 'eliminar_item'); ?>                 
                        <tr>
                            <td><?php echo $counter; ?></td>
                            <td><?php echo $row->tipo_impuesto; ?></td>
                            <td><?php echo $row->codigo_impuesto; ?></td>
                            <td><?php echo $row->valor; ?></td>
                            <td><?php echo $row->valor_retencion; ?></td>
                            <td><?php echo $row->impuesto; ?></td>
                            <td><?php echo $row->fecha_inicio; ?></td>
                            <td><?php echo $row->fecha_fin; ?></td>
                            <td><?= ($row->estado == Impuestos::ACTIVO) ? '<span class="label label-success" rel="tooltip">Activo</span>' : '<span class="label label-danger" rel="tooltip">Bloqueado</span>'; ?></td>
                            <?php if (Session::get('perfil_id') <= Perfil::ADMIN) { ?>
                                <td class="btn-actions">
                                    <?= DwHtml::buttonTable('Modificar impuesto', "$modulo/modificar/$key_mod/", NULL, 'info', 'fa-edit'); ?>
                                    <?php if ($row->estado == TablasTipos::ACTIVO) { ?>
                                        <?php echo DwHtml::buttonTable('Bloquear impuesto', "$modulo/estado/inactivar/$key_ina/", null, 'success', 'fa-flag'); ?>
                                    <?php } else { ?>
                                        <?php echo DwHtml::buttonTable('Reactivar impuesto', "$modulo/estado/reactivar/$key_rea/", null, 'danger', 'fa-flag'); ?>
                                    <?php } ?>
                                    <?php echo DwHtml::buttonTable('Eliminar impuesto', "$modulo/eliminar/$key_del/", array('class' => 'js-confirm', 'confirm-title' => 'Eliminar impuesto', 'confirm-body' => 'Está seguro de eliminar este impuesto? <br />Recuerda que esta operación no se puede reversar.'), 'danger', 'fa-ban'); ?>
                                </td>
                            <?php } ?>
                        </tr>
                        <?php $counter++; ?>
                    <?php endforeach; ?>
                </tbody>
            </table>
            <?php View::partial('paginators/default', false, array('page' => $impuestos, 'url' => "$modulo/ver/$key/$order/")); ?>
        </div>
    </div>

    <footer class="main-footer no-print">


</section>
