<?php View::flash(); ?>

<?php View::process($page_module, $page_title, $set_title); ?>


<section class="content">

    <div class="box">

        <div class="box-header">
            <?php if (Session::get('perfil_id') <= Perfil::SUPERVISOR) { ?>
                <?php echo DwHtml::button("$modulo/agregar/", 'AGREGAR', array('class' => 'btn-success'), 'fa-plus', APP_AJAX); ?>
            <?php } ?>
        </div>

        <div class="box-header">
            <h3 class="box-title">Lista de Marcas</h3>
            <div class="box-tools">
                <?php echo DwForm::open("$modulo/buscar/", 'post'); ?>
                <div class="input-group input-group-sm" style="width: 150px;">
                    <input type="text" name="value" class="form-control pull-right" placeholder="Buscar...">
                    <div class="input-group-btn">
                        <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                    </div>
                </div>
                <?php echo DwForm::close(); ?>
            </div>
        </div>

        <div class="box-body">

            <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">

                <table class="table table-hover">
                    <tbody>
                        <tr>
                            <th>NUM</th>
                            <th>FOTO</th>
                            <th>MARCA</th>
                            <th>ESTADO</th>
                            <?php if (Session::get('perfil_id') != Perfil::SUPERVISOR) { ?>
                                <th>ACCIONES</th>
                            <?php } ?>
                        </tr>
                        <?php foreach ($marcas->items as $marca) { ?>
                            <?php $key_upd = Security::setKey($marca->id, 'upd_marca'); ?>
                            <tr>
                                <td><?php echo $marcas->counter; ?></td>
                                <td><?= empty($marca->imagen) ? DwHtml::img("upload/marcas/default.jpg", NULL, array('id' => 'img-marcas', 'width' => '80')) : DwHtml::img("upload/marcas/$marca->imagen", "$marca->imagen", array('id' => 'img-marcas', 'width' => '80')); ?></td>
                                <td><?= $marca->marca; ?></td>
                                <td><?= ($marca->activo == Marca::ACTIVO) ? '<span class="label label-success">Activo</span>' : '<span class="label label-danger">Bloqueado</span>'; ?></td>
                                <?php if (Session::get('perfil_id') != Perfil::SUPERVISOR) { ?>
                                    <td>
                                        <?= DwHtml::buttonTable('Modificar marca', "$modulo/editar/$key_upd/", NULL, 'warning', 'fa-edit'); ?>
                                    </td>
                                <?php } ?>
                            </tr>
                            <?php $marcas->counter++; ?>
                        <?php } ?>
                    </tbody>
                </table>

                <?php View::partial('paginators/default', false, array('page' => $marcas, 'url' => "$modulo/listar/$order/")); ?>

            </div>

        </div>

    </div>

</section>