<?php View::flash(); ?>

<div class="row">

    <div class="section-title">
        <h3 class="title">Mi Foto</h3>
    </div>

    <div class="col-md-12">
        <!-- The time line -->
        <ul class="timeline">
            <!-- timeline time label -->
            <li class="time-label">
                <span class="bg-red">
                    <?= $usuario->nombre; ?> <?= $usuario->apellido; ?>
                </span>
            </li>
            <!-- /.timeline-label -->
            <!-- timeline item -->
            <li>
                <!-- timeline icon -->
                <i class="fa fa-database bg-blue"></i>
                <div class="timeline-item">
                    <span class="time"><i class="fa fa-clock-o"></i> <?= date("Y-m-d", strtotime($usuario->usuario_at)) ?></span>


                    <h3 class="timeline-header"><a href="#">Creado</a> ...</h3>

                    <div class="timeline-body">
                        <!-- info row -->
                        <div class="row invoice-info">
                            <div class="col-sm-4 invoice-col">
                                <address>
                                    <strong>NOMBRE: </strong><?= $usuario->nombre; ?> <?= $usuario->apellido; ?><br>
                                    <strong>USUARIO: </strong><?= $usuario->login; ?><br>
                                    <strong>EMAIL: </strong><?= $usuario->email; ?><br>
                                    <strong>C&Oacute; </strong> <?= $usuario->pool; ?>
                                </address>
                            </div>
                        </div>
                        <!-- /.row -->
                    </div>

                </div>
            </li>
            <!-- END timeline item -->
            <!-- timeline item -->
            <li>
                <i class="fa fa-camera bg-purple"></i>

                <div class="timeline-item">
                    <span class="time"><i class="fa fa-clock-o"></i> <?= date("Y-m-d", strtotime($usuario->usuario_at)) ?></span>

                    <h3 class="timeline-header"><a href="#">Subir Imagen</a> ...</h3>

                    <div class="timeline-body">

                        <div class="row">
                            <div class="col-md-8 fileupload-buttonbar">

                                <div class="col-md-4">
                                    <span class="btn btn-success fileinput-button">
                                        <i class="icon-plus icon-white"></i>
                                        <span>Seleccionar fotografía...</span>
                                        <input id="fotografia" type="file" name="fotografia" class="input-large">
                                    </span>
                                </div>

                                <div id="upload-progress" class="col-md-4 span4 fileupload-progress fade">                                                    
                                    <div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                                        <div class="bar" style="width:0%;"></div>
                                    </div>
                                </div>

                                <div class="span5 dw-text-right">
                                    <div class="span5 dw-picture-profile dw-text-center dw-text-middle dw-shadow-dark" style="margin-top: 5px"> 
                                        <?= DwHtml::img("upload/personas/$usuario->fotografia", "$usuario->nombre", array('id' => 'img-persona')); ?>
                                    </div>
                                </div>

                            </div>                   

                        </div>

                    </div>
                </div>

            </li>
            <!-- END timeline item -->
        </ul>
        <div class="box box-info">
            <div class="box-footer text-right">
                <?= DwHtml::button("$modulo/datos/", 'REGRESAR', array('class' => 'btn-info'), 'fa-reply'); ?>
            </div>
        </div>

    </div>

</div>


<?php View::partial('jquery.file-upload'); ?>

<script type="text/javascript">
    $('#fotografia').fileupload({
        url: '<?php echo PUBLIC_PATH . "cuenta/cliente/uploadimg/" . Security::setKey($usuario->id, 'upl_foto'); ?>',
        dataType: 'json',
        maxFileSize: 9999999, //2MB
        acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/i,
        start: function () {
            $("#flash-message").empty();
            $('#upload-progress').removeClass('fade');
            $('.bar').parent().removeClass('progress-danger').addClass('progress-success');
            $('[type=submit]').attr('disabled', 'disabled');
        },
        progress: function (e, data) {
            var progress = parseInt(data.loaded / data.total * 100, 10);
            $('.bar').css('width', progress + '%');
        },
        add: function (e, data) {
            var jqXHR = data.submit()
                    .done(function (result, textStatus, jqXHR) {
                        console.log(result);
                        console.log(textStatus);
                        if (textStatus != 'success' || result.error != false) {
                            $('.bar').parent().removeClass('progress-success').addClass('progress-danger');
                            flashError('Oops! el archivo no se ha podido cargar. <br />Detalle del error: ' + (result.error != false) ? result.error : textStatus);
                        } else {
                            flashValid('El archivo se ha cargado correctamente!');
                            $("#materiales_fotografia").val(result.name);
                            $("#img-persona").attr('src', '<?= PUBLIC_PATH; ?>img/upload/personas/' + result.name);
                        }
                    })
                    .fail(function (jqXHR, textStatus, errorThrown) {
                        if (textStatus != null) {
                            flashError('Oops! el archivo no se ha podido cargar. <br />Detalle del error: ' + textStatus);
                            $('.bar').parent().removeClass('progress-success').addClass('progress-danger');
                            setTimeout(function () {
                                $('#upload-progress').addClass('fade');
                            }, 1000);
                        } else {
                            flashWarning('Oops! al parecer el archivo no es una imágen válida. <br />Intenta con otro archivo.');
                            $('.bar').parent().removeClass('progress-success').addClass('progress-danger');
                            $('#upload-progress').addClass('fade');
                        }
                    })
                    .always(function () {
                        setTimeout(function () {
                            $('#upload-progress').addClass('fade');
                            $('.bar').css('width', '0%');
                        }, 1000);
                        $('[type=submit]').removeAttr('disabled');
                    });
        }
    });
</script>
