<?php View::flash(); ?>

<?php View::process($page_module, $page_title, $set_title); ?>

<section class="content">

    <?= DwForm::open('', 'post', array('id' => 'form', 'class' => 'dw-validate no-ajax')); ?>

    <div class="box box-danger">

        <div class="box-body">

            <div class="row">
                <div class="col-md-3">
                    <?= DwForm::text('orden.numero', array('class' => 'input-readonly mask-num show-error', 'maxlength' => '9'), $orden->numero, 'Número orden'); ?>
                </div>
                <div class="col-md-3">
                    <?php if (Session::get('perfil_id') <= Perfil::ADMIN) { ?>
                        <?= DwForm::date('orden.fecha_emision', array('class' => 'mask-date show-error', 'maxlength' => '10'), $orden->fecha_emision, 'Fecha Emisión'); ?>
                    <?php } else { ?>
                        <?= DwForm::text('orden.fecha_emision', array('class' => 'input-readonly mask-date input-readonly show-error', 'maxlength' => '10'), $orden->fecha_emision, 'Fecha Emisión'); ?>
                    <?php } ?>
                </div>
                <div class="col-md-5">
                    <?= DwForm::dbSelect('orden.empresas_id', array('ruc', 'nombres', 'razon_social'), array('empresas', 'getListaEmpresas', Empresas::CLIENTE), 'Seleccione un Cliente', array('class' => 'select2 input-required show-errors'), $orden->empresas_id, 'Cliente:'); ?>
                </div>
                <div class="col-md-1">
                    <?= DwForm::label('<b>Editar Cliente.</b>', 'modifica'); ?>
                    <?= DwForm::check('modifica', NULL, array('class' => 'modifica'), FALSE); ?>
                </div>
            </div>

            <div class="row" id="list-datos">
                <div class="col-md-6">
                    <?= DwForm::text('orden.nombres', array('class' => 'input-break input-readonly mask-text show-error', 'maxlength' => '200'), $orden->nombres, 'Nombres'); ?>
                </div>
                <div class="col-md-6">
                    <?= DwForm::text('orden.razon_social', array('class' => 'input-break input-readonly input-required mask-text show-error', 'maxlength' => '200'), $orden->razon_social, 'Raz&oacute;n Social / Apellidos'); ?>
                </div>
                <div class="col-md-2">
                    <?= DwForm::dbSelect('orden.tipo_documento', 'titulo', array('params/tablas_tipos', 'getListadoTablasTipos', TablasTipos::TIPO_IDENTIFICACION), 'Seleccione una Opción', array('class' => 'input-break input-readonly show-errors'), $orden->tipo_documento, 'Tipo Documento'); ?>
                </div>
                <div class="col-md-2">
                    <?= DwForm::text('orden.ruc', array('class' => 'input-break input-readonly input-required show-error', 'maxlength' => '13'), $orden->ruc, 'Cédula o RUC'); ?>
                </div>
                <div class="col-md-2">
                    <?= DwForm::text('orden.telefono', array('class' => 'input-break input-readonly input-required show-error', 'maxlength' => '9'), $orden->telefono, 'Télefono'); ?>
                </div>
                <div class="col-md-3"> 
                    <?= DwForm::text('orden.email', array('class' => 'input-break input-readonly input-required mask-email show-error', 'maxlength' => '60'), $orden->email, 'Email'); ?>
                </div>
                <div class="col-md-3"> 
                    <?= DwForm::textarea('orden.direccion', array('class' => 'input-break input-readonly input-required mask-text show-error', 'maxlength' => '60'), $orden->direccion, 'Direccion'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-md-2">
                    <?= DwForm::select('orden.garantia', array('' => 'Seleccione', '1 AÑO' => '1 AÑO', '6 MESES' => '6 MESES', '3 MESES' => '3 MESES', '18 MESES' => '18 MESES', 'SIN GARANTIA' => 'SIN GARANTIA'), array('class' => 'input-required show-errors'), $orden->garantia, 'Garantia'); ?>
                </div>
                <div class="col-md-2">
                    <?= DwForm::select('orden.vigencia', array('' => 'Seleccione', '5 DIAS' => '5 DIAS', '10 DIAS' => '10 DIAS', '15 DIAS' => '15 DIAS', '30 DIAS' => '30 DIAS', 'BAJO PEDIDO' => 'BAJO PEDIDO'), array('class' => 'input-required show-errors'), $orden->vigencia, 'Vigencia Dìas'); ?>
                </div>
                <div class="col-md-2">
                    <?= DwForm::select('orden.pagos', array('' => 'Seleccione', 'efectivo' => 'EFECTIVO', 'credito' => 'CREDITO EMPRESAS', 'cheque' => 'CHEQUE', 'payphone' => 'PAYPHONE', 'entrega' => 'CONTRA ENTREGA'), array('class' => 'input-required show-errors'), $orden->pagos, 'Forma de Pago'); ?>
                </div>
                <div class="col-md-2">
                    <?= DwForm::text('orden.tiempo_entrega', array('class' => 'input-required mask-text show-error', 'maxlength' => '4'), $orden->tiempo_entrega, 'Tiempo Entrega (Hrs)'); ?>
                </div>
                <div class="col-md-2">
                    <?= DwForm::text('orden.envios', array('class' => 'mask-text show-error', 'maxlength' => '10'), $orden->envios, 'Costo Entrega'); ?>
                </div>
                <div class="col-md-2">
                    <?= DwForm::text('orden.entregas', array('class' => 'mask-text show-error', 'maxlength' => '20'), $orden->entregas, 'Sector Entrega'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <?= DwForm::textarea('orden.observacion', array('class' => 'mask-text show-error', 'maxlength' => '500'), NULL, 'Observacion'); ?>
                </div>
            </div>

            <div class="row">
                <div class="form-actions">
                    <?= DwButton::save('Guardar información'); ?>
                    <?php echo DwForm::cancel(); ?>
                </div>
            </div>

        </div>

    </div>

    <?= DwForm::close(); ?>

</section>
<script type="text/javascript">
    $(document).ready(function () {
        $('.modifica').on('click', function () {
            $("#flash-message").empty();
            if ($(this).is(':checked')) {
                $(".modifica").val('1');
                $(".input-break ").removeAttr("readonly").attr('required', 'required');
                flashValid("Ingrese los datos del cliente");
            } else {
                $(".modifica").val('0');
                $(".input-break ").attr("readonly", "true");
            }
        });
        $('#orden_empresas_id').change(function () {
            actual = $(this).val();
            $.ajax({
                type: "POST",
                url: "<?php echo PUBLIC_PATH . 'catalogo/orden/getDatosCliente/'; ?>",
                data: "cliente=" + actual,
                success: function (data) {
                    $("#list-datos").html(data);
                }
            });
        });
    });
</script>