<?php View::flash(); ?>

<?php View::process($page_module, $page_title, $set_title); ?>

<section class="content">

    <!-- /.row -->
    <div class="row">
        <div class="col-xs-12">
            <div class="box">

                <div class="box-header">
                    <?php if (Session::get('perfil_id') <= Perfil::SUPERVISOR) { ?>
                        <?php echo DwHtml::button("$modulo/agregar/", 'AGREGAR', array('class' => 'btn-success'), 'fa-plus', APP_AJAX); ?>
                    <?php } ?>
                </div>

                <div class="box-header">
                    <h3 class="box-title">Lista de Ordenes</h3>
                    <div class="box-tools">
                        <?php echo DwForm::open("$modulo/buscar/", 'post', array('class' => 'no-ajax')); ?>
                        <div class="input-group input-group-sm" style="width: 150px;">
                            <input type="text" name="value" class="form-control pull-right" placeholder="Buscar...">
                            <div class="input-group-btn">
                                <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                            </div>
                        </div>
                        <?php echo DwForm::close(); ?>
                    </div>
                </div>

                <!-- /.box-header -->
                <div class="box-body table-responsive no-padding">

                    <table class="table table-hover">
                        <tr>
                            <th>NUM</th>
                            <th>TIPO ORDEN</th>
                            <th>NUMERO</th>
                            <th>FECHA ORDEN</th>
                            <th>CEDULA/RUC</th>
                            <th>CLIENTE</th>
                            <th>F. PAGO</th>
                            <th>VIGENCIA</th>
                            <th>TOTAL</th>
                            <th>ESTADO</th>
                            <?php if (Session::get('perfil_id') <= Perfil::SUPERVISOR) { ?>
                                <th>ACCIONES</th>
                            <?php } ?>
                        </tr>
                        <?php foreach ($listados->items as $row): ?>
                            <?php $key_shw = Security::setKey($row->id, 'shw_orden'); ?>
                            <?php $key_upd = Security::setKey($row->id, 'upd_orden'); ?>  
                            <tr>
                                <td><?php echo $listados->counter; ?></td>
                                <td><?= ($row->tipo_orden == 'o') ? '<span class="label label-success" rel="tooltip">Orden</span>' : '<span class="label label-info" rel="tooltip">Cotizacion</span>'; ?></td>
                                <td><?= $row->numero; ?></td>
                                <td><?= $row->fecha_emision; ?></td>
                                <td><?= $row->ruc; ?></td>
                                <td><?= $row->nombres . ' ' . $row->razon_social; ?></td>
                                <td><?= $row->pagos; ?></td>
                                <td><?= $row->vigencia; ?></td>
                                <td><?= $row->total; ?></td>
                                <td><?= DwOnline::setEstadoOrden($row->estado_orden); ?></td>
                                <?php if (Session::get('perfil_id') <= Perfil::SUPERVISOR) { ?>
                                    <td class="btn-actions">
                                        <?php echo DwHtml::buttonTable('Ver orden', "$modulo/detalle/$key_shw/", NULL, 'info', 'fa-search'); ?>
                                        <?php if (Session::get('perfil_id') <= Perfil::ADMIN) { ?>
                                            <?php echo DwHtml::buttonTable('Modificar orden', "$modulo/editar/$key_upd/", null, 'warning', 'fa-edit'); ?>
                                        <?php } ?>
                                    </td>
                                <?php } ?>
                            </tr>
                            <?php $listados->counter++; ?>
                        <?php endforeach; ?>
                    </table>
                    <?php View::partial('paginators/default', false, array('page' => $listados, 'url' => "$modulo/listar/$order/")); ?>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>

    </div>

</section>