<?php View::flash(); ?>

<?php View::process($page_module, $page_title, $set_title); ?>

<section class="content">

    <!-- /.row -->
    <div class="row">
        <div class="col-xs-12">
            <div class="box">

                <div class="box-header">
                    <?php if (Session::get('perfil_id') <= Perfil::SUPERVISOR) { ?>
                        <?php echo DwHtml::button("$modulo/agregar/", 'AGREGAR', array('class' => 'btn-success'), 'fa-plus', APP_AJAX); ?>
                        <?php echo DwHtml::button("$modulo/migrar/", 'MIGRAR CLIENTES', array('class' => 'btn-danger'), 'fa-plus', APP_AJAX); ?>
                    <?php } ?>
                </div>

                <div class="box-header">
                    <h3 class="box-title">Lista de Clientes</h3>
                    <div class="box-tools">
                        <?php echo DwForm::open("$modulo/buscar/", 'post', array('class' => 'no-ajax')); ?>
                        <div class="input-group input-group-sm" style="width: 150px;">
                            <input type="text" name="value" class="form-control pull-right" placeholder="Buscar...">
                            <div class="input-group-btn">
                                <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                            </div>
                        </div>
                        <?php echo DwForm::close(); ?>
                    </div>
                </div>

                <!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                    <table class="table table-hover">
                        <tr>
                            <th>NUM</th>
                            <th>CIUDAD</th>
                            <th>RUC</th>
                            <th>NOMBRES</th>
                            <th>RAZON SOCIAL</th>
                            <th>TELEFONO</th>
                            <th>EXT.</th>
                            <th>DIRECION</th>
                            <th>EMAIL</th>
                            <?php if (Session::get('perfil_id') <= Perfil::SUPERVISOR) { ?>
                                <th>ACCIONES</th>
                            <?php } ?>
                        </tr>
                        <?php foreach ($empresas->items as $prov): ?>
                            <?php $key_shw = Security::setKey($prov->id, 'shw_empresa'); ?>
                            <?php $key_upd = Security::setKey($prov->id, 'upd_empresa'); ?>                
                            <tr>
                                <td><?php echo $empresas->counter; ?></td>
                                <td><?= $prov->ciudad; ?></td>
                                <td><?= $prov->ruc; ?></td>
                                <td><?= $prov->nombres; ?></td>
                                <td><?= $prov->razon_social; ?></td>
                                <td><?= empty($prov->telefono) ? '' : $prov->telefono; ?><?= empty($prov->telefono2) ? '' : ' / ' . $prov->telefono2; ?></td>
                                <td><?= empty($prov->ext) ? '' : $prov->ext; ?></td>
                                <td><?= $prov->direccion; ?></td>
                                <td><?= $prov->email; ?></td>
                                <td class="btn-actions">
                                    <?= DwHtml::buttonTable('Ver empresa', "$modulo/ver/$key_shw/", NULL, 'info', 'fa-search'); ?>
                                    <?php if (Session::get('perfil_id') <= Perfil::ADMIN) { ?>
                                        <?php echo DwHtml::buttonTable('Modificar empresa', "$modulo/editar/$key_upd/", null, 'warning', 'fa-edit'); ?>
                                    <?php } ?>
                                </td>
                            </tr>
                            <?php $empresas->counter++; ?>
                        <?php endforeach; ?>
                    </table>
                    <?php View::partial('paginators/default', false, array('page' => $empresas, 'url' => "$modulo/listar/$order/")); ?>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>

    </div>

</section>