<?php View::flash(); ?>

<?php View::process($page_module, $page_title, $set_title); ?>

<section class="content">

    <div class="box box-danger">

        <div class="box-body">

                <div class="box-header">
                    <?php if (Session::get('perfil_id') == Perfil::SUPER_USUARIO) { ?>
                        <?php echo DwHtml::button("$modulo/agregar/", 'agregar', NULL, 'fa-plus', APP_AJAX); ?>
                    <?php } ?>
                </div>

                <div class="container-overflow">

                    <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
                        <thead>
                            <tr>
                                <th>NUM</th>
                                <th class="col-hidden" data-search="nombre" data-order="nombre">NOMBRE TABLA</th>
                                <th data-order="">ABREVIATURA</th>
                                <th data-order="">DETALLE</th>
                                <th class="col-hidden" data-order="activo">ESTADO</th>
                                <?php if (Session::get('perfil_id') == Perfil::SUPER_USUARIO) { ?>
                                    <th class="btn-actions col-blocked text-center  ">ACCIONES</th>
                                <?php } ?>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($tablas->items as $tabla): ?>
                                <?php $key_upd = Security::setKey($tabla->id, 'upd_tabla'); ?>
                                <?php $key_show = Security::setKey($tabla->id, 'shw_tabla'); ?>
                                <tr>
                                    <td><?php echo $tablas->counter; ?></td>
                                    <td><?= $tabla->nombre; ?></td>
                                    <td><?= $tabla->abreviatura; ?></td>
                                    <td><?= $tabla->detalle; ?></td>
                                    <td><?= ($tabla->activo == TablasTipos::ACTIVO) ? '<span class="label label-success" rel="tooltip">Activo</span>' : '<span class="label label-danger" rel="tooltip">Bloqueado</span>'; ?></td>
                                    <?php if (Session::get('perfil_id') == Perfil::SUPER_USUARIO) { ?>
                                        <td class="btn-actions">
                                            <?php echo DwHtml::buttonTable('Ver tabla', "$modulo/ver/$key_show/", null, 'info', 'fa-search'); ?>
                                            <?= DwHtml::buttonTable('Modificar tabla', "$modulo/editar/$key_upd/", NULL, 'info', 'fa-edit'); ?>
                                        </td>
                                    <?php } ?>
                                </tr>
                                <?php $tablas->counter++; ?>
                            <?php endforeach; ?>
                        </tbody>
                    </table>

                </div>

                <?php View::partial('paginators/default', false, array('page' => $tablas, 'url' => "$modulo/listar/$order/")); ?>

        </div>

    </div>

</section>