<?php View::flash(); ?>

<?php View::process($page_module, $page_title, $set_title); ?>

<section class="content">

    <div class="box box-danger">

        <div class="box-body">

            <?= DwForm::open('', 'post', array('id' => 'form', 'class' => 'dw-validate  no-ajax')); ?>

            <div class="row">
                <div class="col-md-3">
                    <?= DwForm::dbSelect('tablas.tablas_id', 'nombre', array('tablas', 'getListadoTablas', Tablas::ACTIVO), 'Seleccione una Opción', array('class' => 'input-xlarge input-required show-errors'), NULL, 'Nombre Tabla'); ?>
                </div>
                <div class="col-md-3">
                    <?= DwForm::text('tablas.codigo', array('class' => 'input-readonly mask-text show-error', 'maxlength' => '4'), NULL, 'Código'); ?>
                </div>
                <div class="col-md-3">
                    <?= DwForm::text('tablas.largo', array('class' => 'input-required mask-num show-error', 'maxlength' => '5'), NULL, 'Porcentaje'); ?>
                </div>
                <div class="col-md-3">
                    <?= DwForm::text('tablas.titulo', array('class' => 'input-required mask-text show-error', 'maxlength' => '500'), NULL, 'Nombre Columna'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-md-3">
                    <?= DwForm::text('tablas.detalle', array('class' => 'input-required mask-text show-error', 'maxlength' => '60'), NULL, 'Detalle'); ?>
                </div>
                <div class="col-md-3">
                    <?= DwForm::number('tablas.orden', array('class' => 'input-required mask-num show-error', 'maxlength' => '2'), NULL, 'Orden'); ?>
                </div>
                <div class="col-md-3">
                    <?= DwForm::text('tablas.valida', array('class' => 'mask-num show-error', 'maxlength' => '5'), NULL, 'Valor Valida'); ?>
                </div>
                <div class="col-md-3">
                    <?= DwForm::select('tablas.activo', array('' => 'Seleccione', '1' => 'ACTIVO', '0' => 'BLOQUEADO'), array('class' => 'input-break input-required mask-pint show-errors'), NULL, 'Estado Tabla'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <?= DwForm::textarea('tablas.url_envio', array('class' => 'mask-text show-error', 'maxlength' => '120'), NULL, 'URL ENVIO'); ?>
                </div>
                <div class="col-md-6">
                    <?= DwForm::textarea('tablas.url_consulta', array('class' => 'mask-text show-error', 'maxlength' => '120'), NULL, 'URL CONSULTA'); ?>
                </div>
            </div>

            <div class="box box-info">
                <div class="box-footer">
                    <div class="pull-right">
                        <?php echo DwForm::send('Agregar contenido'); ?>
                        <?php echo DwForm::cancel(); ?>
                    </div>
                </div>
            </div>

            <?php echo DwForm::close(); ?>

        </div>

    </div>

</section>