<?php View::flash(); ?>

<?php View::process($page_module, $page_title, $set_title); ?>

<section class="content">

    <?= DwForm::open('', 'post', array('id' => 'form', 'class' => 'dw-validate  no-ajax')); ?>

    <div class="box box-danger">

        <div class="box-body">

            <div class="row">
                <div class="col-md-6">
                    <?= DwForm::text('utilidad.desde', array('class' => 'input-lower input-required input-required mask-num show-error', 'maxlength' => '10'), NULL, 'Valor Desde'); ?>
                </div>
                <div class="col-md-6">
                    <?= DwForm::text('utilidad.hasta', array('class' => 'input-lower input-required input-required mask-num show-error', 'maxlength' => '10'), NULL, 'Valor Hasta'); ?>
                </div>            
            </div>

            <div class="row">
                <div class="col-md-6">
                    <?= DwForm::text('utilidad.porcentaje', array('class' => 'input-lower input-required input-required mask-num show-error', 'maxlength' => '5'), NULL, 'Porcentaje'); ?>
                </div>
                <div class="col-md-6">
                    <?= DwForm::select('utilidad.tipo', array('' => 'Seleccione', 'u' => 'UTILIDAD', 'd' => 'DISTRIBUIDOR', 'i' => 'IVA'), array('class' => 'input-break input-medium input-required mask-pint show-errors'), NULL, 'TIPO COSTO'); ?>
                </div>
            </div>

            <div class="box box-info">
                <div class="box-footer">
                    <?php echo DwForm::send('Guardar utilidad'); ?>
                    <?php echo DwForm::cancel(); ?>
                </div>
            </div>

        </div>

    </div>

    <?php echo DwForm::close(); ?>

</section>