<?php View::flash(); ?>

<?php View::process($page_module, $page_title, $set_title); ?>


<section class="content">

    <div class="box">

        <div class="box-body">

            <div class="box-body table-responsive no-padding">

                <table class="table table-hover">
                    <tbody>
                        <tr>
                            <th>NUM</th>
                            <th>FECHA</th>
                            <th>HORA</th>
                            <th>NOMBRE</th>
                            <th>APELLIDO</th>
                            <th>IP</th>
                            <th>TIPO ACCESO</th>
                        </tr>
                        <?php foreach ($accesos->items as $acceso): ?>
                            <tr>
                                <td><?php echo $accesos->counter; ?></td>
                                <td><?php echo date("Y-m-d", strtotime($acceso->acceso_at)); ?></td>
                                <td><?php echo date("H:i:s", strtotime($acceso->acceso_at)); ?></td>
                                <td><?php echo $acceso->nombre; ?></td>
                                <td><?php echo $acceso->apellido; ?></td>
                                <td><?php echo $acceso->ip; ?></td>
                                <td><?php echo ($acceso->tipo_acceso == Acceso::ENTRADA) ? '<span class="label label-success">Entrada</span>' : '<span class="label label-danger">Salida</span>'; ?></td>
                            </tr>
                            <?php $accesos->counter++; ?>
                        <?php endforeach; ?>
                    </tbody>
                </table>

                <?php View::partial('paginators/default', false, array('page' => $accesos, 'url' => "sistema/accesos/listar/$order/")); ?>

            </div>

        </div>

    </div>

</section>