<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <?= DwHtml::img('upload/personas/' . (empty(Session::get('foto')) ? 'default.png' : Session::get('foto')), 'User ', array('class' => 'img-circle', 'style' => 'width: 160px;')); ?>
            </div>
            <div class="pull-left info">
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <?php echo DwMenuBackend::desktop(); ?>

    </section>
    <!-- /.sidebar -->
</aside>