<?php View::flash(); ?>

<?php View::process($page_module, $page_title, $set_title); ?>

<section class="invoice">

    <div class="row">
        <div class="col-xs-12">
            <h2 class="page-header">
                <i class="fa fa-list"></i> FACTURA #<?= $factura->numero ?>
                <small class="pull-right">FECHA: <?= date('Y-m-d') ?></small>
            </h2>
        </div>
    </div>

    <section id="new">
        <h4 class="page-header">Informaci&oacute;n CLIENTE</h4>
    </section>

    <?php echo DwForm::open("facturacion/items/agregar/", '', array('id' => 'form-articulo', 'class' => 'flash-validate', 'data-to' => 'flash-message')); ?>

    <div class="row invoice-info">

        <div class="box-body">

            <div class="row">
                <div class="col-md-3">
                    <?= DwForm::dbSelect('cliente.tipo_documento', 'titulo', array('params/tablas_tipos', 'getListaTablasActivas', TablasTipos::TIPO_IDENTIFICACION), 'Seleccione una Opción', array('class' => 'input-break input-required show-errors'), NULL, 'Tipo Documento'); ?>
                </div>
                <div class="col-md-3" id="div_tipo_documento">
                    <?= DwForm::text('cliente.ruc', array('class' => 'input-break mask-pint show-error', 'autocomplete' => 'off', 'maxlength' => '13', 'placeholder' => '1712092939'), NULL, 'Buscar: Cédula o RUC'); ?>
                </div>
                <div class="col-md-3">
                    <?= DwForm::dbSelect('cliente.ciudad_id', 'ciudad', array('config/ciudad', 'getListadoCiudad', Recurso::ACTIVO), 'Seleccione una Ciudad', array('class' => 'input-break input-required mask-pint show-errors'), 14, 'Ciudad'); ?>
                </div>
                <div class="col-md-3">
                    <?= DwForm::dbSelect('cliente.tipo_cliente', 'titulo', array('params/tablas_tipos', 'getListaTablasActivas', TablasTipos::TIPO_CLIENTE), 'Seleccione una Opción', array('class' => 'input-break input-required show-errors'), NULL, 'Tipo Cliente'); ?>
                </div>
            </div>

            <div class="row" id="div_tipo_cliente">
                <div class="col-md-6">
                    <?= DwForm::text('cliente.nombres', array('class' => 'input-break mask-text show-error', 'autocomplete' => 'off', 'maxlength' => '60', 'placeholder' => 'Nombres Cliente'), NULL, 'Nombres Cliente'); ?>
                </div>
                <div class="col-md-6">                    
                    <?= DwForm::text('cliente.apellidos', array('class' => 'input-break input-required mask-text show-error', 'autocomplete' => 'off', 'maxlength' => '150', 'placeholder' => 'Apellidos / Razon Social'), NULL, 'Apellidos Cliente / Razón Social'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <?= DwForm::text('cliente.direccion', array('class' => 'input-break input-required mask-text show-error', 'maxlength' => '200', 'placeholder' => 'Calle principal, Numero, Calle Secunadaria'), NULL, 'Dirección'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-md-2">
                    <?= DwForm::text('cliente.telefono', array('class' => 'input-break mask-pint show-error', 'maxlength' => '9', 'placeholder' => '022652109'), NULL, 'Teléfono 1'); ?>
                </div>
                <div class="col-md-2">
                    <?= DwForm::text('cliente.celular', array('class' => 'input-break mask-pint show-error', 'maxlength' => '10', 'placeholder' => '0983323210'), NULL, 'Celular'); ?>
                </div>
                <div class="col-md-4">
                    <?= DwForm::email('cliente.email', array('class' => 'input-break input-required mask-email show-error', 'autocomplete' => 'off', 'maxlength' => '100', 'placeholder' => 'info@dominio.com'), NULL, 'Email 1'); ?>
                </div>
                <div class="col-md-4">
                    <?= DwForm::email('cliente.email2', array('class' => 'input-break mask-email show-error', 'autocomplete' => 'off', 'maxlength' => '100', 'placeholder' => 'info@dominio.com'), NULL, 'Email 2'); ?>
                </div>
            </div>

            <section id="new">
                <h4 class="page-header">Detalle Factura</h4>
            </section>

            <div class="row">
                <div class="col-md-11">
                    <?php echo DwForm::select('detalle.articulos_id', '', array('class' => 'select2 js-articulos input-required js-list', 'data-to' => PUBLIC_PATH . 'facturacion/items/getPrecio', 'data-update' => 'div-precio-articulo'), NULL, 'Articulo  (codigo | articulo | marca | precio | stock)'); ?>
                </div>
            </div>

            <div class="row">
                <div id='div-precio-articulo'>
                    <div class="col-md-1">
                        <?= DwForm::text('detalle.cantidad', array('class' => 'input-break input-readonly mask-num show-error', 'autocomplete' => 'off', 'maxlength' => '4'), NULL, 'Cantidad'); ?>
                    </div>
                    <div class="col-md-2">
                        <?= DwForm::text('detalle.valor_unitario', array('class' => 'input-break input-readonly input-required show-error', 'autocomplete' => 'off', 'maxlength' => '15'), NULL, 'Precio'); ?>
                    </div>
                    <div class="col-md-2">
                        <?= DwForm::text('con_iva', array('class' => 'input-break input-readonly show-error', 'maxlength' => '15'), NULL, 'PRECIO CON IVA'); ?>
                    </div>
                    <div class="col-md-2">
                        <?= DwForm::text('precio_venta', array('class' => 'input-break input-readonly input-required show-error', 'maxlength' => '15'), NULL, 'PRECIO SUGERIDO'); ?>
                    </div>
                    <div class="col-md-2">
                        <?= DwForm::text('detalle.descuento', array('class' => 'input-break input-readonly show-error', 'maxlength' => '15'), NULL, 'Descuento %'); ?>
                    </div>
                    <div class="col-md-1">
                        <?= DwForm::text('stock', array('class' => 'input-break input-required input-readonly show-error', 'maxlength' => '15'), NULL, 'Stock'); ?>
                    </div>
                </div>
                <div class="col-md-2 text-center">
                    <?= DwForm::label('<b>boton guardar: </b>', 'label', array('style' => 'color: #ffffff;')); ?>
                    <?php echo DwForm::send('Agregar', 'fa-save', array('id' => 'btn-guarda-articulo', 'class' => 'btn btn-success btn-guarda-articulo')); ?>
                </div>
            </div>

            <?php echo DwForm::close(); ?>

            <?php echo DwImpuestos::getDetalleFactura($factura->id); ?>

            <?php echo DwImpuestos::getPieFactura($factura->id); ?>


            <div class="col-sm-4 invoice-col">
                From
                <address>
                    <strong>Admin, Inc.</strong><br>
                    795 Folsom Ave, Suite 600<br>
                    San Francisco, CA 94107<br>
                    Phone: (804) 123-5432<br>
                    Email: info@almasaeedstudio.com
                </address>
            </div>
            <!-- /.col -->
            <div class="col-sm-4 invoice-col">
                To
                <address>
                    <strong>John Doe</strong><br>
                    795 Folsom Ave, Suite 600<br>
                    San Francisco, CA 94107<br>
                    Phone: (555) 539-1037<br>
                    Email: john.doe@example.com
                </address>
            </div>
            <!-- /.col -->
            <div class="col-sm-4 invoice-col">
                <b>Invoice #007612</b><br>
                <br>
                <b>Order ID:</b> 4F3S8J<br>
                <b>Payment Due:</b> 2/22/2014<br>
                <b>Account:</b> 968-34567
            </div>
            <!-- /.col -->
        </div>

        <div class="row">
            <!-- accepted payments column -->
            <div class="col-xs-6">
                <p class="lead">Payment Methods:</p>
                <img src="../../dist/img/credit/visa.png" alt="Visa">
                <img src="../../dist/img/credit/mastercard.png" alt="Mastercard">
                <img src="../../dist/img/credit/american-express.png" alt="American Express">
                <img src="../../dist/img/credit/paypal2.png" alt="Paypal">

                <p class="text-muted well well-sm no-shadow" style="margin-top: 10px;">
                    Etsy doostang zoodles disqus groupon greplin oooj voxy zoodles, weebly ning heekya handango imeem plugg
                    dopplr jibjab, movity jajah plickers sifteo edmodo ifttt zimbra.
                </p>
            </div>
            <!-- /.col -->
            <div class="col-xs-6">
                <p class="lead">Amount Due 2/22/2014</p>
                <button type="button" class="btn btn-success pull-right" onclick="traer()"><i class="fa fa-credit-card"></i> Traer Articulos
                </button>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>ITEM</th>
                                <th>ARTICULO</th>
                                <td>CANTIDAD</td>
                                <td>PRECIO</td>
                            </tr>                            
                        </thead>
                        <tbody id="contenido">
                            <tr>
                                <th>Shipping:</th>
                                <td>$5.80</td>
                                <td>$5.80</td>
                                <td>$5.80</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->

        <!-- this row will not appear when printing -->
        <div class="row no-print">
            <div class="col-xs-12">
                <a href="invoice-print.html" target="_blank" class="btn btn-default"><i class="fa fa-print"></i> Print</a>
                <button type="button" class="btn btn-success pull-right"><i class="fa fa-credit-card"></i> Submit Payment
                </button>
                <button type="button" class="btn btn-primary pull-right" style="margin-right: 5px;">
                    <i class="fa fa-download"></i> Generate PDF
                </button>
            </div>
        </div>
    </div>
</section>

<script type="text/javascript">
    var contenido = document.querySelector('#contenido');
    function traer() {
        fetch("<?php echo PUBLIC_PATH . 'facturacion/items/getArticulos/'; ?>")
                .then(res => res.json())
                .then(datos => {
//                    console.log(datos)
                    tabla(datos)
                })
    }
    function tabla(datos) {
//        console.log(datos)
        contenido.innerHTML = ''
        for (let valor of datos) {
            contenido.innerHTML += `
                <tr>
                    <th>${valor.id}</th>
                    <td>${valor.nombre}</td>
                    <td>$5.80</td>
                    <td>$5.80</td>
                </tr>
`
        }

    }


    $(document).ready(function () {
        $("#cliente_ruc").focus();
        $("#cliente_ruc").on('change', function () {
            var codigo = $(this).val();
            $.ajax({
                async: true,
                type: "POST",
                dataType: "json",
                contentType: "application/x-www-form-urlencoded; charset=UTF-8",
                url: "<?php echo PUBLIC_PATH . 'facturacion/items/getClienteFactura/'; ?>",
                data: "numero=" + codigo,
                beforeSend: antesEnvio,
                success: mostrarDatos,
                timeout: 4000,
                error: errorEnvio
            });
            return false;
        });
    });
    function antesEnvio() {
//        $("#log").text("Se procesa la función 'antesEnvio()' antes de enviarse los datos...");
    }
    function errorEnvio() {
        flashError('Error en el envio');
    }
    function mostrarDatos(datos) {
        $("#flash-message").empty();
        form = $('#form-articulo');
        if (datos.success === true) {
            $("#cliente_nombres").val(datos.nombres);
            $("#cliente_apellidos").val(datos.apellidos);
            $("#cliente_direccion").val(datos.direccion);
            $("#cliente_telefono").val(datos.telefono);
            $("#cliente_celular").val(datos.celular);
            $("#cliente_email").val(datos.email);
            $("#cliente_email2").val(datos.email2);
            $("#cliente_tipo_documento").append(datos.tipo_select).val(datos.tipo_documento);
            $("#cliente_tipo_cliente").append(datos.tipo_select).val(datos.tipo_cliente);
            $("#cliente_ciudad_id").append(datos.tipo_select).val(datos.ciudad_id);
            flashValid('Existe Cliente...');
        } else {
            $('.input-break', form).val('');
            flashError('Cliente nuevo...');
        }
    }
</script>