<?php View::flash(); ?>
<style>
    @media (min-width: 1200px) {
        .container {
            width: 1078px;
        }
        .logo_products {
            padding: 2em 0 1em;
        }
    }
</style>
<div class="container shell-view">
    
    <?php View::process($page_module, $page_title, $set_title); ?>

    
    <?php echo DwForm::open(); ?>
    
    <ul class="nav nav-tabs hidden-xs">
        <li class="active"><a href="#tab1" data-toggle="tab">Información personal</a></li>
        <li><a href="#tab2" data-toggle="tab">Información de la cuenta</a></li>
        <li><a href="#tab3" data-toggle="tab">Cargar imágen</a></li>
    </ul>
    <ul class="nav nav-pills nav-stacked visible-xs">    
        <li class="active"><a href="#tab1" data-toggle="tab">Información personal</a></li>
        <li><a href="#tab2" data-toggle="tab">Información de la cuenta</a></li>
        <li><a href="#tab3" data-toggle="tab">Cargar imágen</a></li>
    </ul>

    <div class="tab-content">
        
        <div class="tab-pane active" id="tab1">
            
            <div class="row">
                <div class="col-md-6">
                    <?php echo DwForm::text('usuario.nombre', array('class'=>'input-required','readonly'=>'readonly'), $usuario->nombre, 'Nombre'); ?>
                </div>
                <div class="col-md-6">
                    <?php echo DwForm::text('usuario.apellido', array('class'=>'input-required','readonly'=>'readonly'), $usuario->apellido, 'Apellido'); ?>
                </div>
            </div>
            
            <div class="row">
                <div class="col-md-6">
                    <?php echo DwForm::email('usuario.email', array('class'=>'input-email input-required mask-email','readonly'=>'readonly'), $usuario->email, 'Email'); ?>
                </div>
            </div>
                
        </div>
        
        <div class="tab-pane" id="tab2">
            
            <div class="row">
                <div class="col-md-6">                    
                    <?php echo DwForm::text('usuario.login', array('class'=>'input-readonly input-lower'), $usuario->login, 'Usuario'); ?>
                </div>
                <div class="col-md-6">
                    <?php echo DwForm::oneSelect('usuario.perfil_id', $usuario->perfil, array('class'=>'input-readonly'), 'Perfil'); ?>
                </div>
            </div>
            
            <div class="row">
                <div class="col-md-6">
                    <?php echo DwForm::pass('oldpassword', array('class'=>''), '', 'Contraseña anterior'); ?>
                </div>
            </div>
            
            <div class="row">
                <div class="col-md-6">
                    <?php echo DwForm::pass('usuario.password', array('class'=>'input-pass'), '', 'Contraseña'); ?>
                </div>
                <div class="col-md-6">
                    <?php echo DwForm::pass('repassword', array('class'=>'input-repass', 'data-equalto'=>'usuario_password'), '', 'Confirmación'); ?>
                </div>
            </div>
            
        </div>
        
        <div class="tab-pane" id="tab3">
            
            <div class="row fileupload-buttonbar">

                <div class="col-md-6" style="margin-bottom: 20px;">

                    <div class="row">

                        <div class="col-md-6">
                            <?php echo DwForm::upload('fotografia', array('data-to'=>PUBLIC_PATH.'micuenta/datos/upload/', 'data-size'=>5000000, 'data-files'=>'images', 'data-success'=>'loadImg'), 'Fotografía'); ?>
                        </div>

                        <div class="col-md-6">
                            <div class="picture-profile text-center text-middle shadow-dark" style="margin: 5px auto 0px;">
                                <?php echo DwHtml::img("upload/personas/$usuario->fotografia", "$usuario->nombre $usuario->apellido", array('id'=>'img-usuario')); ?>
                            </div>
                        </div>

                    </div>

                </div>

            </div>

            <?php echo DwForm::hidden('usuario.fotografia', NULL, $usuario->fotografia); ?>
            <?php echo DwForm::hidden('usuario.app_ajax', NULL, $usuario->app_ajax); ?>
            <?php echo DwForm::hidden('usuario.tema', NULL, $usuario->tema); ?>
            <?php echo DwForm::hidden('usuario.datagrid', NULL, $usuario->datagrid); ?>
            
        </div>        
        
    </div>
    
    <div class="row">
        <div class="form-actions">
            <?php echo DwForm::send('Actualizar mis datos'); ?>
            <?php echo DwForm::cancel(); ?>
            <?php echo DwForm::focus('usuario.nombre'); ?>
        </div>
    </div>

   
    <?php echo DwForm::close(); ?>
    
</div>

<script type="text/javascript">
    
    function loadImg(result, input) {
        $("#usuario_fotografia").val(result.name);
        $("#img-usuario").attr('src', '<?php echo PUBLIC_PATH; ?>img/upload/personas/'+result.name);        
    }
    
</script>