<?php View::flash(); ?>

<?php View::process($page_module, $page_title, $set_title); ?>


<section class="content">

    <div class="box">

        <div class="box-header">
            <?php if (Session::get('perfil_id') <= Perfil::SUPERVISOR) { ?>
                <?= DwHtml::button("catalogo/excel/mails", 'upload', array('class' => 'btn-danger btn-cargarexcel'), 'fa-cloud-upload'); ?>
                <?php echo DwHtml::button("$modulo/valida/", 'CHECK', array('class' => 'btn-success'), 'fa-check', APP_AJAX); ?>
                <?php echo DwHtml::button("$modulo/bajas/", 'BAJAS', array('class' => 'btn-danger'), 'fa-circle', APP_AJAX); ?>
                <?php echo DwHtml::button("$modulo/boletines/", 'BOLETINES', array('class' => 'btn-warning'), 'fa-envelope', APP_AJAX); ?>
                <?= DwButton::report("mail/productos/", 'pdf', 'Plantilla', 'Plantilla'); ?>
            <?php } ?>
        </div>

        <div class="box-header">
            <h3 class="box-title">Lista de Suscriptores</h3>
            <div class="box-tools">
                <?php echo DwForm::open("$modulo/buscar/", 'post'); ?>
                <div class="input-group input-group-sm" style="width: 150px;">
                    <input type="text" name="value" class="form-control pull-right" placeholder="Buscar...">
                    <div class="input-group-btn">
                        <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                    </div>
                </div>
                <?php echo DwForm::close(); ?>
            </div>
        </div>

        <div class="box-body">

            <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">

                <table class="table table-hover">
                    <tbody>
                        <tr>
                            <th>NUM</th>
                            <th>CORREO</th>
                            <th>NOMBRE</th>
                            <th>DOMINIO</th>
                            <th>ESTATUS</th>
                            <th>NUEVO</th>
                            <th>PROMO</th>
                            <th>ESTADO</th>
                            <?php if (Session::get('perfil_id') != Perfil::SUPERVISOR) { ?>
                                <th>ACCIONES</th>
                            <?php } ?>
                        </tr>
                        <?php foreach ($correos->items as $row) { ?>
                            <?php $key_upd = Security::setKey($row->id, 'upd_marca'); ?>
                            <tr>
                                <td><?php echo $correos->counter; ?></td>
                                <td><?= $row->correo; ?></td>
                                <td><?= $row->nombres; ?></td>
                                <td><?= $row->dominio; ?></td>
                                <td><?= $row->estatus; ?></td>
                                <td><?= ($row->nuevo == Suscripcion::ACTIVO) ? '<span class="label label-success">SI</span>' : '<span class="label label-danger">NO</span>'; ?></td>
                                <td><?= ($row->promo == Suscripcion::ACTIVO) ? '<span class="label label-success">SI</span>' : '<span class="label label-danger">NO</span>'; ?></td>
                                <td><?= ($row->estado == Suscripcion::ACTIVO) ? '<span class="label label-success">Activo</span>' : '<span class="label label-danger">Bloqueado</span>'; ?></td>
                                <?php if (Session::get('perfil_id') != Perfil::SUPERVISOR) { ?>
                                    <td>
                                        <?= DwHtml::buttonTable('Modificar marca', "$modulo/editar/$key_upd/", NULL, 'warning', 'fa-edit'); ?>
                                    </td>
                                <?php } ?>
                            </tr>
                            <?php $correos->counter++; ?>
                        <?php } ?>
                    </tbody>
                </table>

                <?php View::partial('paginators/default', false, array('page' => $correos, 'url' => "$modulo/listar/$order/")); ?>

            </div>

        </div>

    </div>

</section>