<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv = "X-UA-Compatible" content = "IE=Edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <TITLE>Tecnologia a Domicilio</TITLE>
        <meta http-equiv="Content-Type" content="text/html; ISO-8859-1">
        <META NAME="DC.Language" SCHEME="RFC1766" CONTENT="Spanish">
        <META NAME="AUTHOR" CONTENT="Asdin">
        <META NAME="REPLY-TO" CONTENT="soporte@asdinec.com">
        <LINK REV="made" href="mailto:soporte@asdinec.com">
        <META NAME="DESCRIPTION" CONTENT="Bienvenidos a Asdin, servicio a domicilio Quito, celulares, computadoras, televisores, impresoras, Pedidos: 0984022304">
        <META NAME="KEYWORDS" CONTENT="jbl,jbl go,samsung,notebook,venta celulares,servicio a domicilio">
        <META NAME="Resource-type" CONTENT="Index">
        <META NAME="DateCreated" CONTENT="Sun, 28 Mayo 2012 00:00:00 GMT+1">
        <META NAME="Revisit-after" CONTENT="3 days">
        <META NAME="robots" content="ALL">
        <link rel="canonical" href="http://www.asdinec.com"/>
        <link rel="alternate" hreflang="es" href="http://www.asdinec.com" />

        <link href="https://fonts.googleapis.com/css?family=Hind:400,700" rel="stylesheet">
        <?php // Tag::css('frontend/bootstrap/bootstrap.min'); ?>
        <?php Tag::css('backend/themes/template/bootstrap.min'); ?>
        <?php Tag::css('frontend/bootstrap/slick'); ?>
        <?php Tag::css('frontend/bootstrap/slick-theme'); ?>
        <?php Tag::css('frontend/bootstrap/nouislider.min'); ?>
        <?php Tag::css('font-awesome.min'); ?>
        <?php Tag::css('frontend/bootstrap/style'); ?>
        <?php Tag::css('backend/themes/template/select2.min'); ?>
        <?php Tag::css('backend/themes/template/AdminLTE.min'); ?>
        <?php Tag::css('backend/themes/template/_all-skins.min'); ?>
        <?php Tag::css('file-upload'); ?>
        <?php Tag::css('backend/style'); ?>
        <?php Tag::css('frontend/carro'); ?>
        <?php echo Html::includeCss(); ?>

        <!--[if lt IE 9]>
                  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
                  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
                <![endif]-->
        <?php echo Tag::js('template/jquery/jquery.min') . PHP_EOL; ?>
        <?php echo Tag::js('template/jquery/bootstrap.min') . PHP_EOL; ?>

        <script>
            (function (i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r;
                i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
                a = s.createElement(o),
                        m = s.getElementsByTagName(o)[0];
                a.async = 1;
                a.src = g;
                m.parentNode.insertBefore(a, m)
            })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

            ga('create', 'UA-100778464-1', 'auto');
            ga('send', 'pageview');

            !function(f,b,e,v,n,t,s)
            {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
            n.callMethod.apply(n,arguments):n.queue.push(arguments)};
            if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
            n.queue=[];t=b.createElement(e);t.async=!0;
            t.src=v;s=b.getElementsByTagName(e)[0];
            s.parentNode.insertBefore(t,s)}(window, document,'script',
            'https://connect.facebook.net/en_US/fbevents.js');
            fbq('init', '462463561105562');
          </script>
          <noscript><img height="1" width="1" style="display:none"
            src="https://www.facebook.com/tr?id=462463561105562&ev=PageView&noscript=1"
          /></noscript>
</head>

<body onload="actualizaCarrito()">
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>
    <!-- HEADER -->
    <?php View::partial('frontend/header'); ?>
    <!-- /HEADER -->

    <!-- NAVIGATION -->
    <div id="navigation">
        <!-- container -->
        <div class="container">
            <?php View::partial('frontend/menu'); ?>
        </div>
        <!-- /container -->
    </div>
    <!-- /NAVIGATION -->

    <!-- HOME -->
    <div id="home">
        <!-- container -->
        <div class="container">
            <!-- home wrap -->
            <div class="home-wrap">
                <!-- home slick -->

                <?php View::partial('frontend/banners'); ?>

                <!-- /home slick -->
            </div>
            <!-- /home wrap -->
        </div>
        <!-- /container -->
    </div>
    <!-- /HOME -->

    <?php // View::partial('frontend/home'); ?>

    <!-- section -->
    <?php View::content(); ?>
    <!-- /section -->

    <!-- FOOTER -->
    <?php View::partial('frontend/footer'); ?>
    <!-- /FOOTER -->

    <!-- jQuery Plugins -->
    <?php echo Tag::js('frontend/bootstrap/slick.min'); ?>
    <?php echo Tag::js('frontend/bootstrap/nouislider.min'); ?>
    <?php echo Tag::js('frontend/bootstrap/jquery.zoom.min'); ?>
    <?php echo Tag::js('frontend/bootstrap/main'); ?>
    <?php echo Tag::js('frontend/owl.carousel.min'); ?>
    <?php echo Tag::js('frontend/carousel'); ?>

    <?php echo Tag::js('moment/moment.min') . PHP_EOL; ?>
    <?php echo Tag::js('jquery/jquery.kumbiaphp') . PHP_EOL; ?>
    <?php echo Tag::js('jquery/jquery.keyfilter') . PHP_EOL; ?>
    <?php echo Tag::js('jquery/jquery.kgrid') . PHP_EOL; ?>
    <?php echo Tag::js('jquery/jquery.kload') . PHP_EOL; ?>        
    <?php echo Tag::js('jquery/jquery.spin') . PHP_EOL; ?>        
    
    <?php echo Tag::js('backend') . PHP_EOL; ?>
    <?php echo Tag::js('validador') . PHP_EOL; ?>

    <!-- CART -->
    <?php View::partial('frontend/carrito'); ?>
    <!-- /CART -->
</body>

</html>