<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="<?php echo APP_CHARSET; ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="robots" content="noindex,nofollow" /> 
        <link rel="shortcut icon" href="<?php echo PUBLIC_PATH; ?>img/favicon.ico" type="image/x-icon" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <title><?php echo $page_title; ?></title>
        <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
        <!--     Fonts and icons     -->
        <?php Tag::css('frontend/googleapis.css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons'); ?>
        <?php Tag::css('frontend/font-awesome.min'); ?>
        <?php Tag::css('frontend/material-kit.css?v=2.0.5'); ?>
        <?php Tag::css('frontend/demo'); ?>
        <?php Tag::css('frontend/style'); ?>
        <?php echo Html::includeCss(); ?>
    </head>

    <body class="login-page sidebar-collapse">

<nav class="navbar navbar-transparent navbar-color-on-scroll fixed-top navbar-expand-lg" color-on-scroll="100" id="sectionsNav">
    <noscript><h5 style="text-align: center;">¡Tu navegador no soporta Javascript!.. Activa el uso de Javascript en tu navegador.</h5></noscript>
    <div class="container">
        <div class="navbar-translate">
            <?php echo DwHtml::link("", 'INICIO', array('class' => 'navbar-brand'), 'fa-home'); ?>
            <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="sr-only">Toggle navigation</span>
                <span class="navbar-toggler-icon"></span>
                <span class="navbar-toggler-icon"></span>
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
                <li class="dropdown nav-item">
                    <div class="dropdown-menu dropdown-with-icons">
                        <a href="#" class="dropdown-item">
                            <i class="material-icons">layers</i> Todos
                        </a>
                        <a href="#" class="dropdown-item">
                            <i class="material-icons">content_paste</i> Introducci&oacute;n
                        </a>
                    </div>
                </li>
                <li class="nav-item">
                    <?php echo DwHtml::link("cuenta/login/entrar/", 'Ingresar', array('class' => 'nav-link'), 'fa-sign-in'); ?>
                </li>
                <li class="nav-item">
                    <a class="nav-link" rel="tooltip" title="" data-placement="bottom" href="tel:+593984022304" data-original-title="Llamar Celular"><i class="fa fa-phone"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" rel="tooltip" title="" data-placement="bottom" href="https://api.whatsapp.com/send?phone=593984022304" target="_blank" data-original-title="Enviar WhatsApp"><i class="fa fa-whatsapp"></i></a>
                </li>
            </ul>
        </div>
    </div>
</nav>

        <div class="page-header header-filter" style="background-image: url('../../../img/frontend/bg7.jpg'); background-size: cover; background-position: top center;">
            <?php View::content(); ?>
        </div>

        <!--  End Modal -->
<footer class="footer" data-background-color="black">
    <div class="container">
        <nav class="float-left">
            <ul>
                <li>
                    <?php echo DwHtml::link("", 'INICIO', NULL, 'fa-home'); ?>
                </li>
            </ul>
        </nav>
        <div class="copyright float-right">
            Copyright &copy;
            <script>
                document.write(new Date().getFullYear())
            </script>, Desarrollado por
            <a href="http://asdinec.com" target="_blank"><b>AsdinEc</b></a> Todos los derechos reservados.
            <b>Versión</b> <?php echo APP_VERSION; ?>
        </div>
    </div>
</footer>

        <!--   Core JS Files   -->
        <?php echo Tag::js('frontend/core/jquery.min') . PHP_EOL; ?>
        <?php echo Tag::js('frontend/core/popper.min') . PHP_EOL; ?>
        <?php echo Tag::js('frontend/core/bootstrap-material-design.min') . PHP_EOL; ?>
        <?php echo Tag::js('frontend/plugins/moment.min') . PHP_EOL; ?>
        <?php echo Tag::js('frontend/plugins/bootstrap-datetimepicker') . PHP_EOL; ?>
        <?php echo Tag::js('frontend/plugins/nouislider.min') . PHP_EOL; ?>
        <?php echo Tag::js('frontend/material-kit.js?v=2.0.5') . PHP_EOL; ?>
    </body>

</html>