<?php View::flash(); ?>

<?php View::process($page_module, $page_title, $set_title); ?>

<section class="content">

    <?= DwForm::open('', 'post', array('id' => 'form', 'class' => 'dw-validate')); ?>

    <div class="row">

        <div class="col-xs-12">
            <div class="nav-tabs-custom">
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#fa-home" data-toggle="tab">Informaci&oacute;n personal</a></li>
                    <li><a href="#segunda" data-toggle="tab">Informaci&oacute;n de la cuenta</a></li>
                    <li><a href="#tercera" data-toggle="tab">Cargar im&aacute;gen</a></li>
                </ul>

                <div class="tab-content">

                    <div class="tab-pane active" id="fa-home">

                        <section id="new">
                            <h4 class="page-header">Informaci&oacute;n</h4>
                        </section>

                        <div class="row">
                            <div class="col-md-6">
                                <?= DwForm::dbSelect('usuario.establecimientos_id', array('sucursal', 'direccion'), array('establecimientos', 'getListadoEstablecimientos'), 'Seleccione Establecimiento', array('class' => 'form-control select2 input-required mask-pint show-errors'), NULL, 'Establecimiento'); ?>
                            </div>
                            <div class="col-md-3">
                                <?= DwForm::dbSelect('usuario.tipo_documento', 'titulo', array('tablas_tipos', 'getListaTablasActivas', 'tid'), 'Seleccione una Opción', array('class' => 'input-xlarge input-required mask-pint show-errors'), NULL, 'Tipo de identificación'); ?>
                            </div>
                            <div class="col-md-3" id="div_tipo_documento">
                                <?php echo DwForm::text('usuario.ruc', array('class' => 'input-required mask-alphanum'), NULL, 'Ruc/Cédula'); ?>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">                    
                                <?php echo DwForm::text('usuario.nombre', array('class' => 'input-required'), NULL, 'Nombres'); ?>
                            </div>
                            <div class="col-md-6">
                                <?php echo DwForm::text('usuario.apellido', array('class' => 'input-required'), NULL, 'Apellidos'); ?>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <?php echo DwForm::email('usuario.email', array('class' => 'input-email mask-email'), NULL, 'Email'); ?>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label>Teléfono:</label>
                                    <div class="input-group">
                                        <div class="input-group-addon"><i class="fa fa-phone"></i></div>
                                        <input id="usuario_telefono" name="usuario[telefono]" type="text" class="form-control" data-inputmask='"mask": "(99) 999-9999"' data-mask>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label>Celular:</label>
                                    <div class="input-group">
                                        <div class="input-group-addon"><i class="fa fa-phone"></i></div>
                                        <input id="usuario_celular" name="usuario[celular]" type="text" class="form-control" data-inputmask='"mask": "(999) 999-9999"' data-mask>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <?php echo DwForm::textarea('usuario.direccion', array('class' => 'input-required mask-text'), NULL, 'Dirección'); ?>
                            </div>
                        </div>

                    </div>

                    <div class="tab-pane" id="segunda">

                        <div class="row">
                            <div class="col-md-6">                    
                                <?php echo DwForm::text('usuario.login', array('class' => 'input-lower input-required'), NULL, 'Usuario'); ?>
                            </div>
                            <div class="col-md-6">
                                <?php echo DwForm::dbSelect('usuario.perfil_id', 'perfil', array('sistema/perfil', 'getListadoPerfil', Perfil::ACTIVO), NULL, array('class' => 'input-required'), 5, 'Perfil'); ?>
                            </div>
                        </div>

                        <div class="row">                
                            <div class="col-md-6">
                                <?php echo DwForm::number('usuario.datagrid', array('class' => 'input-integer input-required mask-pint'), 30, 'Cantidad de datos por página', 'Esta información se utiliza en los listados de informaciones y reportes'); ?>
                            </div>
                        </div>


                        <div class="row">
                            <div class="col-md-6">
                                <?php echo DwForm::pass('usuario.password', array('class' => 'input-pass'), '', 'Contraseña'); ?>
                            </div>
                            <div class="col-md-6">
                                <?php echo DwForm::pass('repassword', array('class' => 'input-repass', 'data-equalto' => 'usuario_password'), '', 'Confirmación'); ?>
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-actions">
                                <?= DwButton::save('Guardar Usuario'); ?>
                            </div>
                        </div>

                    </div>

                    <div class="tab-pane" id="tercera">

                        <div class="row fileupload-buttonbar">

                            <div class="col-md-6" style="margin-bottom: 20px;">

                                <div class="row">

                                    <div class="col-md-6">
                                        <?php echo DwForm::upload('fotografia', array('data-to' => PUBLIC_PATH . 'cuenta/usuarios/upload/', 'data-size' => 5000000, 'data-files' => 'images', 'data-success' => 'loadImg'), 'Fotografía'); ?>
                                    </div>

                                    <div class="col-md-6">
                                        <div class="picture-profile text-center text-middle shadow-dark" style="margin: 5px auto 0px;">
                                            <?php echo DwHtml::img("upload/personas/default.png", "Fotografía", array('id' => 'img-usuario')); ?>
                                        </div>
                                    </div>

                                </div>

                            </div>

                        </div>

                        <?php echo DwForm::hidden('usuario.fotografia', NULL, 'default.png'); ?>

                        <div class="box box-info">
                            <div class="box-footer">
                                <?php echo DwForm::send('Crear usuario'); ?>
                                <?php echo DwForm::cancel(); ?>
                                <?php echo DwForm::focus('usuario.nombre'); ?>
                            </div>
                        </div>

                    </div>

                </div>

            </div>

        </div>

        <?php echo DwForm::close(); ?>

</section>

<script type="text/javascript">

    function loadImg(result, input) {
        $("#usuario_fotografia").val(result.name);
        $("#img-usuario").attr('src', '<?php echo PUBLIC_PATH; ?>img/upload/personas/' + result.name);
    }

</script>