<?php View::flash(); ?>

<?php View::process($page_module, $page_title, $set_title); ?>

<section class="content">

    <div class="box-header">
        <?php echo DwHtml::button("$modulo/agregar/", 'agregar', array('class' => 'btn-success'), 'fa-check-square-o', APP_AJAX); ?>
    </div>

    <!-- /.row -->
    <div class="row">
        <div class="col-xs-12">
            <div class="box">

                <div class="box-header">
                    <h3 class="box-title">Lista de Usuarios</h3>
                    <div class="box-tools">
                        <?php echo DwForm::open("$modulo/buscar/", 'post'); ?>
                        <div class="input-group input-group-sm" style="width: 150px;">
                            <input type="text" name="value" class="form-control pull-right" placeholder="Buscar...">
                            <div class="input-group-btn">
                                <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                            </div>
                        </div>
                        <?php echo DwForm::close(); ?>
                    </div>
                </div>

                <!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                    <table class="table table-hover">
                        <tr>
                            <th>ID</th>
                            <th>CIUDAD</th>
                            <th>ESTABLECIMIENTO</th>
                            <th>USUARIO</th>
                            <th>NOMBRES</th>
                            <th>APELLIDOS</th>
                            <th>EMAIL</th>
                            <th>CARGO</th>
                            <th>ESTADO</th>
                            <th>ACCIONES</th>
                        </tr>
                        <?php foreach ($usuarios->items as $usuario): ?>
                            <?php $key_shw = Security::setKey($usuario->id, 'shw_usuario'); ?>
                            <?php $key_psw = Security::setKey($usuario->id, 'psw_usuario'); ?>
                            <?php $key_ina = Security::setKey($usuario->id, 'bloquear_usuario'); ?>
                            <?php $key_rea = Security::setKey($usuario->id, 'reactivar_usuario'); ?>
                            <tr>
                                <td><?php echo $usuarios->counter; ?></td>
                                <td><?php echo $usuario->ciudad; ?></td>
                                <td><?php echo $usuario->sucursal; ?></td>
                                <td><?php echo $usuario->login; ?></td>
                                <td><?php echo $usuario->nombre; ?></td>
                                <td><?php echo $usuario->apellido; ?></td>
                                <td><?php echo $usuario->email; ?></td>
                                <td><?php echo $usuario->perfil; ?></td>
                                <td><?php
                                    echo ($usuario->estado_usuario == EstadoUsuario::ACTIVO) ? '<span class="label label-success" title="' . $usuario->descripcion . '" rel="tooltip">Activo</span>' : '<span class="label label-danger" title="' . $usuario->descripcion . '" rel="tooltip">Bloqueado</span>';
                                    ;
                                    ?></td>
                                <td>
                                    <?php echo DwHtml::buttonTable('Ver usuario', "$modulo/ver/$key_shw/", NULL, 'info', 'fa-search'); ?>                            
                                    <?php if (Session::get('perfil_id') != Perfil::SUPERVISOR) { ?>
                                        <?php echo DwHtml::buttonTable('Cambiar Clave', "$modulo/clave/$key_psw/", NULL, 'warning', 'fa-key'); ?>                            
                                        <?php if ($usuario->estado_usuario == EstadoUsuario::ACTIVO) { ?>
                                            <?php echo DwHtml::buttonTable('Bloquear usuario', "$modulo/estado/bloquear/$key_ina/", NULL, 'success', 'fa-flag'); ?>
                                        <?php } else { ?>
                                            <?php echo DwHtml::buttonTable('Reactivar usuario', "$modulo/estado/reactivar/$key_rea/", NULL, 'danger', 'fa-flag'); ?>
                                        <?php } ?>
                                    <?php } ?>
                                </td>
                            </tr>
                            <?php $usuarios->counter++; ?>
                        <?php endforeach; ?>
                    </table>
                    <?php View::partial('paginators/default', false, array('page' => $usuarios, 'url' => "$modulo/listar/$order/")); ?>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>

    </div>

</section>