<!DOCTYPE html>
<html lang="es">
    <head>
        <title><?php echo $page_title; ?></title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta charset="<?php echo APP_CHARSET; ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <?php Tag::css('frontend/googleapis.css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons'); ?>
        <?php Tag::css('frontend/font-awesome.min'); ?>
        <?php Tag::css('frontend/material-kit.css?v=2.0.5'); ?>
        <?php Tag::css('frontend/demo'); ?>
        <?php Tag::css('frontend/style'); ?>
        <?php echo Html::includeCss(); ?>
        <?php if (!APP_LOCAL) { ?>
            <link href="http://fonts.googleapis.com/css?family=Play:400,700" rel="stylesheet" type="text/css">
        <?php } ?>

        <?php echo Tag::js('jquery/jquery.min') . PHP_EOL; ?>

    </head>
    <body class="login-page sidebar-collapse">

        <?php View::partial('frontend/header_update'); ?>

        <div class="page-header header-filter" style="background-image: url('img/frontend/bg7.jpg'); background-size: cover; background-position: top center;">

            <div class="container">
                <div class="row">
                    <div class="col-md-12 ml-auto mr-auto">
                        <?php View::flash(); ?>

                        <div class="container-fluid dw-shell-view">
                            <div class="row">
                                <div class="col-md-4 dw-text-center">
                                    <br />
                                    <i class="fa fa-cogs" style="font-size: 150px;"></i>
                                </div>
                                <div class="col-md-8 dw-text-left">
                                    <h2>En estos momentos estamos en proceso de mantenimiento.</h2>
                                    <br />
                                    <h3>Por favor ingresa en  <?php echo APP_UPDATE_TIME; ?>.</h3>
                                    <br />
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>

        </div>

    </body>

</html>
