<?php View::flash(); ?>

<?php View::process($page_module, $page_title, $set_title); ?>

<section class="content">

    <div class="box-header">
        <?php if (Session::get('perfil_id') <= Perfil::ADMIN) { ?>
            <?php echo DwHtml::button("$modulo/agregar/", 'agregar', NULL, 'fa-check-square-o', APP_AJAX); ?>
        <?php } ?>
        <?php echo DwHtml::button("$modulo/listar/", 'listar', NULL, 'fa-check', APP_AJAX); ?>

    </div>

    <!-- /.row -->
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Lista de Proveedores</h3>
                    <div class="box-tools">
                        <?php echo DwForm::open("$modulo/buscar/", 'post'); ?>
                        <div class="input-group input-group-sm" style="width: 150px;">
                            <input type="text" name="value" class="form-control pull-right" placeholder="Buscar...">
                            <div class="input-group-btn">
                                <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                            </div>
                        </div>
                        <?php echo DwForm::close(); ?>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                    <table class="table table-hover">
                        <tr>
                            <th>NUM</th>
                            <th>CIUDAD</th>
                            <th>RUC</th>
                            <th>NOMBRES</th>
                            <th>RAZON SOCIAL</th>
                            <th>TELEFONO</th>
                            <th>EXT.</th>
                            <th>DIRECION</th>
                            <th>EMAIL</th>
                            <?php if (Session::get('perfil_id') <= Perfil::ADMIN) { ?>
                                <th>ACCIONES</th>
                            <?php } ?>
                        </tr>
                        <?php if ($proveedores) { ?>
                            <?php foreach ($proveedores->items as $prov): ?>
                                <?php $key_shw = Security::setKey($prov->id, 'shw_proveedor'); ?>
                                <?php $key_upd = Security::setKey($prov->id, 'upd_proveedor'); ?>
                                <tr>
                                    <td><?php echo $proveedores->counter; ?></td>
                                    <td><?php echo ($field == 'ciudad') ? DwUtils::resaltar($value, $prov->ciudad) : $prov->ciudad; ?></td>
                                    <td><?php echo ($field == 'ruc') ? DwUtils::resaltar($value, $prov->ruc) : $prov->ruc; ?></td>
                                    <td><?php echo ($field == 'nombres') ? DwUtils::resaltar($value, $prov->nombres) : $prov->nombres; ?></td>
                                    <td><?php echo ($field == 'razon_social') ? DwUtils::resaltar($value, $prov->razon_social) : $prov->razon_social; ?></td>
                                    <td><?php echo ($field == 'telefono') ? DwUtils::resaltar($value, $prov->telefono) : $prov->telefono; ?></td>
                                    <td><?php echo ($field == 'ext') ? DwUtils::resaltar($value, $prov->ext) : $prov->ext; ?></td>
                                    <td><?php echo ($field == 'direccion') ? DwUtils::resaltar($value, $prov->direccion) : $prov->direccion; ?></td>
                                    <td><?php echo ($field == 'email') ? DwUtils::resaltar($value, $prov->email) : $prov->email; ?></td>
                                    <td class="btn-actions">
                                        <?= DwHtml::buttonTable('Ver proveedor', "$modulo/ver/$key_shw/", NULL, 'info', 'fa-search'); ?>
                                        <?php if (Session::get('perfil_id') <= Perfil::ADMIN) { ?>
                                            <?php echo DwHtml::buttonTable('Modificar proveedor', "$modulo/editar/$key_upd/", null, 'warning', 'fa-edit'); ?>
                                        <?php } ?>
                                    </td>
                                </tr>
                                <?php $proveedores->counter++; ?>
                            <?php endforeach; ?>
                        <?php } ?>
                    </table>
                    <?php View::partial('paginators/default', false, array('page' => $proveedores, 'url' => "$modulo/buscar/$field/$value/$order/")); ?>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>

    </div>

</section>