<?php View::flash(); ?>

<?php View::process($page_module, $page_title, $set_title); ?>

<section class="content">

    <?= DwForm::open('', 'post', array('id' => 'form', 'class' => 'dw-validate no-ajax')); ?>

    <div class="box box-danger">

        <div class="box-body">

            <div class="row">
                <div class="col-xs-12">
                    <h2 class="page-header">
                        <i class="fa fa-cogs"></i> Establecimiento: <?= $empresa->nombres; ?> | <?= $empresa->sucursal; ?>
                        <small class="pull-right">Fecha: <?= date('Y-m-d'); ?></small>
                    </h2>
                </div>
            </div>

            <div class="row">
                <div class="col-md-8">
                    <?php echo DwForm::text('empresa.razon_social', array('class' => 'input-readonly mask-text show-error', 'maxlength' => '150'), NULL, 'Razón Social'); ?>
                </div>
                <div class="col-md-4">
                    <?php echo DwForm::text('sucursal.sucursal', array('class' => 'input-readonly mask-text show-error', 'maxlength' => '150'), $empresa->sucursal, 'Establecimiento / Sucursal'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <?php echo DwForm::text('contacto.nombre', array('class' => 'input-required mask-text show-error', 'maxlength' => '60'), NULL, 'Nombres'); ?>
                </div>
                <div class="col-md-6">
                    <?php echo DwForm::text('contacto.apellido', array('class' => 'input-required mask-text show-error', 'maxlength' => '60'), NULL, 'Apellidos'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <?php echo DwForm::text('contacto.email', array('class' => 'input-required mask-email show-error', 'maxlength' => '100'), NULL, 'Email'); ?>
                </div>
                <div class="col-md-6">
                    <?php echo DwForm::text('contacto.email2', array('class' => 'mask-email show-error', 'maxlength' => '100'), NULL, 'Email 2'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-md-4">
                    <?php echo DwForm::text('contacto.cargo', array('class' => 'input-required mask-text show-error', 'maxlength' => '45'), NULL, 'Cargo'); ?>
                </div>
                <div class="col-md-4">
                    <?php echo DwForm::text('contacto.celular', array('class' => 'input-required mask-pint   show-error', 'maxlength' => '10'), NULL, 'Celular'); ?>
                </div>
                <div class="col-md-4">
                    <?php echo DwForm::text('contacto.extension', array('class' => 'mask-pint   show-error', 'maxlength' => '10'), NULL, 'Extensión'); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <?php echo DwForm::text('contacto.observacion', array('class' => 'mask-text show-error', 'maxlength' => '100'), NULL, 'Observaciones'); ?>
                </div>
            </div>

            <div class="box box-info">
                <div class="box-footer">
                    <?= DwButton::save('Guardar contacto'); ?>
                    <?= DwButton::back(); ?>
                </div>
            </div>

        </div>

    </div>

    <?php echo DwForm::close(); ?>

</section>
