<?php View::flash(); ?>

<?php View::process($page_module, $page_title, $set_title); ?>

<section class="content">

    <?php echo DwForm::open(); ?>

    <div class="box box-danger">

        <div class="box-body">

            <div class="row">
                <div class="col-md-6">
                    <?php echo DwForm::text('perfil.perfil', array('class' => 'input-lower input-required'), NULL, 'Perfil'); ?>
                </div>
                <div class="col-md-6">
                    <?php echo DwForm::text('perfil.plantilla', array('class' => 'input-lower input-alphanum'), NULL, 'Plantilla', 'La plantilla de sebe ubicar dentro la caperta "templates".'); ?>
                </div>
            </div>

            <div class="box box-info">
                <div class="box-footer">
                    <?php echo DwForm::send('Guardar perfil'); ?>
                    <?php echo DwForm::cancel(); ?>
                    <?php echo DwForm::focus('perfil.perfil'); ?>
                </div>
            </div>

        </div>

    </div>

    <?php echo DwForm::close(); ?>

</section>
