<?php View::flash(); ?>

<?php View::process($page_module, $page_title, $set_title); ?>


<section class="content">

    <div class="box">

        <div class="box-header">
            <?php echo DwHtml::button("$modulo/agregar/", 'AGREGAR', array('class' => 'btn-success'), 'fa-plus', APP_AJAX); ?>
        </div>

        <div class="box-body">

            <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">

                <table class="table table-hover">
                    <tbody>
                        <tr>
                            <th>NUM</th>
                            <th>PERFIL</th>
                            <th>PLANTILLA</th>
                            <th>USUARIOS</th>
                            <th>ESTADO</th>
                            <?php if (Session::get('perfil_id') == Perfil::SUPER_USUARIO) { ?>
                                <th>ACCIONES</th>
                            <?php } ?>
                        </tr>
                        <?php foreach ($perfiles->items as $perfil): ?>
                            <?php $key_show = Security::setKey($perfil->id, 'show_perfil'); ?>
                            <?php $key_upd = Security::setKey($perfil->id, 'upd_perfil'); ?>
                            <?php $key_inac = Security::setKey($perfil->id, 'inactivar_perfil'); ?>
                            <?php $key_reac = Security::setKey($perfil->id, 'reactivar_perfil'); ?>
                            <tr>
                                <td><?php echo $perfiles->counter; ?></td>
                                <td><?php echo $perfil->perfil; ?></td>
                                <td><?php echo $perfil->plantilla; ?></td>
                                <td><?php echo $perfil->usuarios; ?></td>
                                <td><?php echo ($perfil->estado == Perfil::ACTIVO) ? '<span class="label label-success">Activo</span>' : '<span class="label label-danger">Bloqueado</span>'; ?></td>
                                <td class="btn-actions">
                                    <?php echo DwHtml::buttonTable('Ver perfil', "sistema/perfiles/ver/$key_show/", null, 'info', 'fa-search'); ?>
                                    <?php echo DwHtml::buttonTable('Modificar perfil', "sistema/perfiles/editar/$key_upd/", null, 'warning', 'fa-edit'); ?>
                                    <?php if ($perfil->estado == Perfil::ACTIVO) { ?>
                                        <?php echo DwHtml::buttonTable('Inactivar perfil', "sistema/perfiles/estado/inactivar/$key_inac/", null, 'success', 'fa-flag'); ?>
                                    <?php } else { ?>
                                        <?php echo DwHtml::buttonTable('Reactivar perfil', "sistema/perfiles/estado/reactivar/$key_reac/", null, 'danger', 'fa-flag'); ?>
                                    <?php } ?>
                                </td>
                            </tr>
                            <?php $perfiles->counter++; ?>
                        <?php endforeach; ?>
                    </tbody>
                </table>

                <?php View::partial('paginators/default', false, array('page' => $perfiles, 'url' => "sistema/perfiles/listar/$order/")); ?>

            </div>

        </div>

    </div>

</section>