<?php View::flash(); ?>

<div class="container shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php View::partial('subnav/cliente/principal', FALSE, array('id' => Session::get('id'))); ?>

    <?php $estado = empty($orden_carrito->id) ? '' : $orden_carrito->activo; ?>

    <?php if ($estado == '0') { ?>
        <div class="btn-toolbar btn-toolbar-top">
            <div class="row">
                <div class="col-md-3">
                    <div class="list-group list-group-alternate">
                        <a href="#" class="list-group-item"><span class="badge badge-default"><?= empty($direccion->tipo_envio) ? 'Sin Dirección' : $tabla_tipo->getNombreTabla($direccion->tipo_envio)->titulo ?></span> <i class="ti ti-email"></i> Enviar a </a> 
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="list-group list-group-alternate">
                        <a href="#" class="list-group-item"><span class="badge badge-default"><?= $carrito_total->total ?></span> <i class="ti ti-email"></i> Articulos Adquiridos </a>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="list-group list-group-alternate">
                        <a href="#" class="list-group-item"><span class="badge badge-default">$ <?= $carrito_suma->total ?></span> <i class="ti ti-email"></i> Total a Pagar </a>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="list-group list-group-alternate">
                        <a href="#" class="list-group-item">Estado: <?= empty($orden_carrito->id) ? '' : DwOnline::setEstadoOrden($orden_carrito->activo) ?></a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-8"></div>
                <div class="col-md-4">
                    <?= empty($direccion->tipo_envio) ? DwHtml::link("micuenta/datos/agregar/" . Security::setKey(Session::get('id'), 'add_direccion'), 'Registrar Direccion', array('class' => 'no-load btn btn-success btn-large'), 'fa fa-pd-expand fa-edit', FALSE) : ''; ?>
                    <?php echo empty($orden_carrito->id) ? '' : DwHtml::button("cliente/cart/confirma/" . Security::setKey($orden_carrito->id, 'cnf_orden'), 'GENERAR PEDIDO', array('class' => 'btn-danger btn-confirma-compra', 'on-confirm' => 'iniciarSincronizacion'), 'fa-money', APP_AJAX); ?>
                </div>
            </div>
        </div>
        <!-- resumen articulos -->
        <div class="privacy">
            <?php if ($orden_carrito) : ?>
                <div class="privacy1">
                    <h4>PEDIDO N.º <?= $orden_carrito->codigo ?></h4>
                    <div class="banner-bottom-grid1 privacy1-grid">
                        <div class="w3agile_event_grids">
                            <?php foreach ($carrito_detalle->items as $carrito): ?>
                                <?php $key_del = Security::setKey($carrito->id, 'eliminar_items'); ?>
                                <?php $key_agr = Security::setKey($carrito->id, 'agrega_items'); ?>
                                <?php $key_qui = Security::setKey($carrito->id, 'quita_items'); ?>
                                <?php $foto = $galeria->getFotoProducto($carrito->mpn)->imagen; ?>

                                <h3><?php echo $carrito_detalle->counter; ?>)  <?php echo $carrito->description; ?></h3>
                                <div class="col-md-12 w3agile_event_grid">
                                    <div class="col-md-2 w3agile_event_grid_left" style="height: 100px;">
                                        <?php echo DwHtml::link('home/detalle/' . $carrito->catalogo_temporal_id . '/' . $carrito->brand, Html::img("upload/productos/$foto", '', array('class' => 'home_section_icon', 'style' => 'width: 100%;height:100%;')), array('data-toggle' => 'tooltip', 'title' => 'Click para Ver Detalles', ''), NULL, FALSE); ?>
                                    </div>
                                    <div class="col-md-7 w3agile_event_grid_right" style="height: 100px;">
                                        <h4>SKU: <?php echo $carrito->mpn; ?> | Marca: <?php echo $carrito->marca; ?></h4>
                                        <p>Cantidad: <?php echo $carrito->cantidad; ?> | Precio: $ <?php echo $carrito->precio_venta; ?> | Total: $ <?php echo $carrito->cantidad * $carrito->precio_venta; ?></p>
                                    </div>
                                    <div class="col-md-3 w3agile_event_grid_right" style="height: 100px;">
                                        <?php if ($orden_carrito->activo == CatalogoOrden::PENDIENTE) { ?>
                                            <?php echo DwHtml::buttonTable('Agregar articulo', "cliente/cart/agregar/$key_agr/", array('class' => 'js-remote', 'title' => 'Agregar artículo', 'data-toggle' => 'tooltip'), 'success', 'fa-plus-square'); ?>
                                            <?php echo DwHtml::buttonTable('Quitar articulo', "cliente/cart/quitar/$key_qui/", array('class' => 'js-confirm', 'title' => 'Agregar artículo', 'data-toggle' => 'tooltip'), 'info', 'fa-minus-square'); ?>
                                            <?php echo DwHtml::buttonTable('Eliminar articulo', "cliente/cart/eliminar/$key_del/", array('class' => 'js-confirm', 'title' => 'Eliminar artículo', 'data-toggle' => 'tooltip'), 'warning', 'fa-times'); ?>
                                        <?php } ?>
                                    </div>
                                    <div class="clearfix"> </div>
                                </div>
                                <?php $carrito_detalle->counter++; ?>
                            <?php endforeach; ?>
                        </div>
                        <br>
                    </div>
                </div>
            <?php else : // Si no hay items  ?>

                <div class="resultadoproductos">
                    <h2 align="center">No hay articulos en el carro!</h2>
                </div>

            <?php endif ?>
        </div>
        <!-- //resumen articulos -->
    <?php } else { ?>
        <h2 align="center">No hay compras pendientes!</h2>
    <?php } ?>

</div>

<div class="modal fade" tabindex="-1" id="form-sicroniza-compra" role="dialog" aria-labelledby="form-sicroniza-compra" aria-hidden="true">

    <div class="modal-dialog">

        <div class="modal-content">

            <?php echo DwForm::open("", '', array('id' => 'form-modal-snc', 'class' => 'flash-validate', 'data-to' => 'flash-message')); ?>

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4>Confirmar Información de Pago!</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6">
                        <?= DwForm::dbSelect('compra.forma_pago', 'titulo', array('tablas_tipos', 'getListadoTablasTipos', TablasTipos::FORMA_PAGO), 'Seleccione una Opción', array('class' => 'input-xlarge input-required mask-pint show-errors'), NULL, 'Forma de Pago'); ?>
                    </div>
                    <div class="col-md-6">
                        <?php echo DwForm::text('compra.valor_cancelado', array('class' => 'input-required mask-num', 'maxlength' => '8', 'placeholder' => empty($carrito_suma->total) ? '' : $carrito_suma->total), NULL, 'Valor Cancelado'); ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <?php echo DwForm::text('compra.documento', array('class' => 'mask-num', 'maxlength' => '12', 'placeholder' => 'Si es deposito/transferencia'), NULL, 'Número de Comprobante'); ?>
                    </div>
                    <div class="col-md-6">
                        <?php echo DwForm::text('compra.institucion', array('class' => 'mask-text', 'maxlength' => '60', 'placeholder' => 'Si es deposito/transferencia'), NULL, 'Institución Financiera'); ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <?php echo DwForm::textarea('compra.observaciones', array('class' => 'mask-text', 'maxlength' => '200', 'placeholder' => 'Observación sobre entrega/pago'), NULL, 'Observaciones de Entrega/Pago'); ?>
                    </div>
                </div>
            </div>

            <?php echo DwForm::hidden('compra.id', NULL, $direccion->id); ?>

            <div class="modal-footer">
                <?php echo DwForm::submit("Enviar", array('class' => 'btn btn-primary')); ?>
                <button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
            </div>
            <?php echo DwForm::close(); ?>

        </div>

    </div>

</div>

<script type="text/javascript">
    function iniciarSincronizacion(refer) {
        $("#flash-message").empty();
        $("#password").val('');
        $("#form-modal-snc").attr('action', refer.attr('href')).attr('data-update', 'false');
        $('#form-sicroniza-compra').modal('show');
        form = $('#form-sicroniza-compra');
        $('.input-break', form).val('');
    }

    $(function () {
        $("#pagina-titulo").append("<?= $titulo ?>");

        $('.btn-confirma-compra').on('click', function (e) {
            var envio = <?= empty($direccion->tipo_envio) ? '0' : $direccion->tipo_envio ?>;
            if (envio === 0) {
                flashError('Debe Ingresar una dirección...<br />Para el envío.');
                flashInfo('Vaya a Mi Cuenta =>  Dirección.');
                return false;
            }
            e.stopImmediatePropagation();
            iniciarSincronizacion($(this));
            return false;
        });
        $("#form-modal-snc").on('submit', function () {
            $('#form-sicroniza-compra').modal('hide');
            flashInfo('Enviando...<br />Espere por favor.');
        });
    });
</script>

