<!DOCTYPE html>
<html lang="es">
    <head>
        <title><?php echo $page_title; ?></title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta charset="<?php echo APP_CHARSET; ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="robots" content="noindex,nofollow" />
        <link rel="icon" href="/<?php echo basename(dirname(APP_PATH)) ?>/img/default/web_ico.gif" type="image/x-icon" />        
        <?php Tag::css('bootstrap/default/css/bootstrap.min'); ?>
        <?php Tag::css('font-awesome.min'); ?>                
        <?php Tag::css('base'); ?>
        <?php Tag::css('style'); ?>
        <?php Tag::css('themes/default/default'); ?>
        <?php echo Html::includeCss() ?>
        <?php if(!APP_LOCAL) { ?>
            <link href="http://fonts.googleapis.com/css?family=Play:400,700" rel="stylesheet" type="text/css">
        <?php } ?>        
        <?php echo Tag::js('jquery/jquery.min').PHP_EOL; ?>                
        <script type="text/javascript">            
            function closePopup() { window.close() }
        </script>
    </head>
    <body style="min-width: 800px;">  
        <script>
            (function (i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r;
                i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
                a = s.createElement(o),
                        m = s.getElementsByTagName(o)[0];
                a.async = 1;
                a.src = g;
                m.parentNode.insertBefore(a, m)
            })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

            ga('create', 'UA-100778464-1', 'auto');
            ga('send', 'pageview');

        </script>        
        <?php View::partial('backend/header_error'); ?>
        
        <div id="dw-shell-load" style="min-height: 350px">             
            <div id="dw-shell-content" class="container-fluid"> 
                <?php View::content(); ?>
            </div>            
        </div>
        
        <?php View::partial('backend/footer'); ?>        
        
    </body>
</html>
